### ISSUE TITLE
Notebook completion doesn't auto-open namespace when an `open` statement exists in a cell below

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#1012]
**Repro Steps:**

In a notebook, do the following:

Cell 1:
```qsharp
%%qsharp

//  invoke completion here and choose `DumpMachine`
```

Cell 2:
```qsharp
%%qsharp

open Microsoft.Quantum.Diagnostics;
```

**Expected:**

Cell 1:
```qsharp
%%qsharp

open Microsoft.Quantum.Diagnostics;
DumpMachine();
```

**Actual:**

Cell 1:
```qsharp
%%qsharp

DumpMachine();
```

The `open` statement is not inserted because the completion list thinks we already have an `open` for this namespace. But since it's in a cell further below, it doesn't apply. This causes `DumpMachine` to fail to be resolved.

Seen in b454828298fc2f505ce6de437167aacf58df3afd

**Comment by sezna** [comment]
Given that we can't control the execution order of cells, this is out of scope for us. This would entail the language service knowing the runtime state of the jupyter environment.
