### ISSUE TITLE
ResourceEstimator: localization

### ISSUE THREAD

**Issue by ivanbasov** [microsoft/qsharp#1030]
1. Numbers and time units formatting are EN/US
2. All descriptions and explanations are in EN/US

Need to consider localization.

**Comment by ivanbasov** [comment]
https://github.com/microsoft/qsharp/pull/985 should reflect numbers format produced in TypeScript. There are also methods on the rust side to be reviewed.

**Comment by sezna** [comment]
Localization of the product would not be isolated to just RE, we would do it holistically (error messages etc).
