### ISSUE TITLE
Resource Estimator scatter chart axis formatting review

### ISSUE THREAD

**Issue by ivanbasov** [microsoft/qsharp#1036]
We may want to consider a bundle of changes such as:
1. Axes ranges definitions (how far should we go from min and from max?)
2. Support of linear scales (currently we support the logarithmic scale only). Linear scales could make sense for small problems.
3. Axes ticks generation algorithms. Current ones would generate in most cases from 1 to 8 ticks. We may want to consider a narrower goal to have something from 2-3 to 5-6 ticks.

**Comment by sezna** [comment]
Closing this as we have no plans to change this UX for now.
