### ISSUE TITLE
RE confusing with comparing formatted time and qubits value

### ISSUE THREAD

**Issue by ivanbasov** [microsoft/qsharp#1062]
Here are two estimates:
* {'physicalQubits': **10236,** 'runtime': **2244000**, 'rqops': 818182, 'breakdown': {'algorithmicLogicalQubits': 18, 'algorithmicLogicalDepth': 16, 'logicalDepth': 102, 'numTstates': 12, 'clockFrequency': 45454.545454545456, 'numTfactories': 1, 'numTfactoryRuns': 12, 'physicalQubitsForTfactories': 5880, 'physicalQubitsForAlgorithm': 4356, ...}}
* {'physicalQubits': **8796**, 'runtime': **2250000**, 'rqops': 1000000, 'breakdown': {'algorithmicLogicalQubits': 18, 'algorithmicLogicalDepth': 16, 'logicalDepth': 125, 'numTstates': 12, 'clockFrequency': 55555.555555555555, 'numTfactories': 1, 'numTfactoryRuns': 12, 'physicalQubitsForTfactories': 5880, 'physicalQubitsForAlgorithm': 2916, ...}}

One of them is better in physicalQubits and another is better respect to the runtime. 

When showing them together and especially on as a tooltip on the chart, we use the following formatted data:
* {'runtime': '**2 millisecs**', 'rqops': '818.18k', 'physicalQubits': '**10.24k**', 'algorithmicLogicalQubits': '18', 'algorithmicLogicalDepth': '16', 'logicalDepth': '102', 'numTstates': '12', 'numTfactories': '1', 'numTfactoryRuns': '12', 'physicalQubitsForAlgorithm': '4.36k', 'physicalQubitsForTfactories': '5.88k', 'physicalQubitsForTfactoriesPercentage': '57.44 %', 'requiredLogicalQubitErrorRate': '1.16e-6', 'requiredLogicalTstateErrorRate': '2.78e-5', ...}
* {'runtime': '**2 millisecs**', 'rqops': '1.00M', 'physicalQubits': '**8.80k**', 'algorithmicLogicalQubits': '18', 'algorithmicLogicalDepth': '16', 'logicalDepth': '125', 'numTstates': '12', 'numTfactories': '1', 'numTfactoryRuns': '12', 'physicalQubitsForAlgorithm': '2.92k', 'physicalQubitsForTfactories': '5.88k', 'physicalQubitsForTfactoriesPercentage': '66.85 %', 'requiredLogicalQubitErrorRate': '1.16e-6', 'requiredLogicalTstateErrorRate': '2.78e-5', ...}

This leads to a confusion because one of estimates dominates another by the number of physical qubits but their formatter runtimes look the same for user. 

A similar scenario could happen for close qubit values.

We may want to consider showing raw full values in some scenarios or re-visit formatting and rounding requirements.

**Comment by sezna** [comment]
Closing this for now, feel free to reopen if we see this being an issue for any users.
