### ISSUE TITLE
Add a legend to the space-time diagram (for screenshot purposes)

### ISSUE THREAD

**Issue by ivanbasov** [microsoft/qsharp#1064]
It should show display: 
- Labels - if provided in Jupyter notebook scenario 
- If not, distinctive columns from the list 
  - Algorithm / run name 
  - Qubit type 
  - Error correction scheme 
  - Error budget 
- If items above do not allow to differentiate between series (e.g. some other parameters such as distillation units were provided), we would display (a), (b), (c) or (1), (2), (3) from corresponding run name extensions.

**Comment by ivanbasov** [comment]
Needs triage because we already attached the full table of results which is used as the legend.

**Comment by sezna** [comment]
Given that the table above can be used as a legend, this improvement likely won't get prioritized.
