### ISSUE TITLE
Remove "Message:" prefix from the output from Message function (running in VS Code)

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1081]
**Describe the bug**

Prefacing the output from the Message function with "Message:" (when running in VS Code) looks very jarring to me, and not what I expect. It makes sense to call out "Result" explicitly, since this happens once per program, and DumpMachine output is large enough that a "DumpMachine" prefix doesn't stand out, but the "Message" prefix looks noisy.

**Screenshots**

For example, in the following example I use newlines to add a break between different parts of the example, and having "Message:" strings makes it look odd:

![image](https://github.com/microsoft/qsharp/assets/10113024/fb463f15-dc56-44dc-b170-302e3a966dcb)

**System information**

- QDK 1.0.33

**Comment by colommar** [comment]
Hi, I'd like to clarify the requirements. Is it ideal to remove the `message:` and directly output the content in the message?

**Comment by tcNickolas** [comment]
Yes
