### ISSUE TITLE
Debugging panel disables the Run button if Q# program throws exception

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1082]
**Describe the bug**

If I get an exception in the output to debug console (for example, qubits released not in zero state), the debugging panel pops up, and the run button doesn't work any longer. At the same time, the debugging panel is not really visible (it's placed over the tabs with different files, so it blends in really well). This can make rerunning the code after fixing the bug very confusing.

**Expected behavior**

Keep the run button enabled in addition to the debugging panel. I don't think there's any state of the program the debugging tool captures at this point that needs to be preserved (debugging the program needs to start from scratch). And I can often fix the exception without going through debugging, so making the panel mandatory is not necessary.

**System information**

- QDK 1.0.33
- Ubuntu

**Comment by billti** [comment]
Seems reasonable that when running without debugging, we shouldn't end up in a debug session if an error occurs (but running under the debugger should).
