### ISSUE TITLE
Rust library panic strings not surfaced in WASM

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#1120]
Currently any panics from the underlying Rust code that come from a web worker all show up as a generic `Error: unexpected` in the VSCode extension. We need to find the right behavior for our WASM panic handling to make sure at the very least the original strings (and possibly later some additional explanatory text) can get surfaced to improve diagnosability without having to attach a debugger.

One current theory: the existing panic hook that gets configured as part of setting up logging is either not configured or not able to function as expected when run from the web worker. Three scenarios today use the web worker: QIR code generation, histogram/shots execution, and resource estimation. We can test with explicit panics in these code paths and find a mechanism (perhaps message passing?) that lets the worker report the panic back to the main thread.

**Comment by minestarks** [comment]
Fixed by #1176
