### ISSUE TITLE
Add citation information to the project

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1128]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a way to point QDK users to a way to cite the QDK in their work. We mention some of the papers describing parts of the QDK in the code, but it's good to make connections like this explicit.

**Describe the solution you'd like**
From browsing GitHub documentation and some example repositories, there are a couple of options we can choose from:

1. Simple CITATION.cff file with the information about the repo itself, similar to the information we had at https://github.com/microsoft/qsharp-language/blob/main/CITATIONS.bib. (This will produce the "Cite this repository" link in the right sidebar)
2. CITATION.cff file with the information about the repo itself + `references` section that can list additional papers we published.
3. Simple CITATION.cff file with the information about the repo itself + "Cite this project" sections in the root readme and the readme in resource_estimator folder giving Bibtex for the citations we want used for citing the whole project vs just the resource estimator.

My personal favorite is option 3, it gives us both a link in the sidebar with a simple bibtex entry that can be copy-pasted and an explicit bibtex for specific sections of the projects.

Here's the list of papers I think make sense as citation material (in addition to this repository itself):
* The original Q# paper https://scholar.google.com/citations?view_op=view_citation&hl=en&user=e5wgoO0AAAAJ&citation_for_view=e5wgoO0AAAAJ:9yKSN-GCB0IC
* The underlying paper for resource estimator https://arxiv.org/abs/2211.07629
* The documentation paper about resource estimator https://scholar.google.com/citations?view_op=view_citation&hl=en&user=e5wgoO0AAAAJ&citation_for_view=e5wgoO0AAAAJ:YsMSGLbcyi4C

Thoughts? Suggestions? Additional papers we have that I missed?

**Comment by swernli** [comment]
I agree with the recommendation of option 3 above. I think it matches our goals of providing more granular citation opportunities for components like the resource estimator while still making it easy to use the top-level citation infrastructure of GitHub.

Thanks for itemizing this for us, Mariia!
