### ISSUE TITLE
Hover: incorrect type shown for lambda passed to generic function

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#1148]
**Code:**

```qsharp
namespace MyQuantumProgram {
    @EntryPoint()
    operation Main() : Result[] {
        let array = [1,2,3];
        ApplyToEach(d => (), array);
        return [];
    }

    // Copied from Microsoft.Quantum.Canon.ApplyToEach
    operation ApplyToEach<'T> (singleElementOperation : ('T => Unit), register : 'T[]) : Unit {
        for item in register {
            singleElementOperation(item);
        }
    }
}
```

Hover over the call to `ApplyToEach` on line 5:

```qsharp
MyQuantumProgram
operation ApplyToEach<'T>(singleElementOperation : ('T => Unit is Param<1>), register : 'T[]) : Unit
```

Hover over the _definition_ of `ApplyToEach`:

```qsharp
MyQuantumProgram
operation ApplyToEach<'T>(singleElementOperation : ('T => Unit), register : 'T[]) : Unit
```

**Expected**

The hover text at the call site should be the same as the one at the definition site.

**Actual**

The hover text at the call site has an extra `is Param<1>` in the type of the lambda.

**Playground link:**

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACm1PwWqDQBS8%2BxVzcwUxtL3ZJqQEj9K02JPksJinXXDfynM9SPHfi6lEKZ3LgzczzAxrS32nK0I%2Bvg%2Ba%2FWDP4hrRFt8BABwz9jKenWGvotvHdSTaG8fItWEVIcUH9UPry8vimdGShxbRI%2FYoH%2BLH%2BOnyfCdfu64dC5fp6ktdsT9ARfGvOlpFQn4QRrn4puB2djucXGfoilqcRW4qcb2rfbK0T06aHSebhD%2BlN8xLWBygesNNS1lLlti%2F3XUpVFjM3T7Z%2BCiGUGN6T4IUYVFe5tkzs5lcO4HxZGF4Va%2F0jP%2Bz1OzaLJ%2BWwVPwA%2FHZ0HifAQAA

Seen in commit a2e65622

**Comment by swernli** [comment]
@ScottCarda-MS, I think this may have been intentional design choice, since at the call site we wanted to show which generic parameter something corresponded to. Can you confirm?

**Comment by ScottCarda-MS** [comment]
> @ScottCarda-MS, I think this may have been intentional design choice, since at the call site we wanted to show which generic parameter something corresponded to. Can you confirm?

This is not related to the generic parameter of the operation, but is actually an unresolved element from the type inference trying to infer the characteristics of the lambda. In this case it should resolve to the empty functor set. However, I've recently seen scenarios where the unresolved element should resolve to non-empty functor sets.

**Comment by swernli** [comment]
Ah, I see. This is not a display issue, but rather an unresolved functor set parameter in the type system itself. This may be intentional as part of the design or it may be a bug, but either way we should try to fix it in the internals. Thanks for clarifying!
