### ISSUE TITLE
I can't accsee a Q# site.

### ISSUE THREAD

**Issue by ForbiddenFuture** [microsoft/qsharp#1151]
https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/algorithms

I was able to access this site last Thursday, but not now.
This site redirects to "https://github.com/microsoft/qsharp/tree/main/library/readme" and shows 404 - page not found
Can I access this site?

**Comment by midhunhk** [comment]
It is only working until: https://learn.microsoft.com/en-us/azure/quantum/user-guide/
which is titled 'The Q# programming language overview'. See if you can use the navigation on the left side to find out what you are looking for.

Maybe they changed or reorganized something in the documentation, I am able to see the page for Grover's Algorithm here.
https://learn.microsoft.com/en-us/azure/quantum/tutorial-qdk-grovers-search?tabs=tabid-copilot

**Comment by billti** [comment]
Sorry for the confusion. With the re-write for the Modern QDK (see https://devblogs.microsoft.com/qsharp/announcing-v1-0-of-the-azure-quantum-development-kit/) the standard library was significantly changed and reduced, and the presence of the docs for the prior QDK was causing confusion. We recently did some updates to try and clarify that, but you shouldn't be landing on a GitHub 404. Looking into it now...

**Comment by swernli** [comment]
The redirect for the link appears to be fixed now.
