### ISSUE TITLE
DrawRandomBool missing in the new QDK

### ISSUE THREAD

**Issue by filipw** [microsoft/qsharp#1170]
**Is your feature request related to a problem? Please describe.**
[DrawRandomBool](https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandombool) is no longer available. On the other hand, both [DrawRandomInt and DrawRandomDouble](https://github.com/microsoft/qsharp/blob/139a8e70a7d16ea9fefc1815ff00f94e701141d4/library/std/random.qs#L51) are there.

**Describe the solution you'd like**
I think it would be useful to have it back for backwards compatibility. I also found it helpful in educational scenarios to orchestrate some parts of the program that required random conditions (especially in the classical part of a hybrid program). It was also nice to be able to pass success probability into it.

**Describe alternatives you've considered**

`DrawRandomBool(0.5)` can be replaced with `DrawRandomInt(0, 1) == 1`
`DrawRandomBool(successProbability)` be replaced with `DrawRandomDouble(0.0, 1.0) < successProbability`

Of course a measurement of a qubit in a specific superposition could also be used.

**Comment by goshua13** [comment]
I can look into this

**Comment by ganap-ram** [comment]
I can take this issue. I believe using the DrawRandomDouble and deriving the bool with given probability can be a good approach. Would also appreciate any guidance (until I get comfortable with the general coding and testing culture) - I don't see a test code for DrawRandomDouble; for DrawRandomBool, I suppose I can create a new test library\src\tests\resources\util.qs where test related to such utilities could be added. Thoughts please!

**Comment by swernli** [comment]
Thanks @ganap-ram! For testing, you are right that we are missing examples for the existing random functions. Part of what was missing when the test infra was first written was a way to set the seed for classical randomness. That now exists:
https://github.com/microsoft/qsharp/blob/0cf6c28e95e67c578b39534a8a248ff93ad7c7a4/compiler/qsc/src/interpret.rs#L285-L287
So you could update `test_expression_with_lib_and_profile_and_sim` utility that the library tests use to always set the classical seed to a fixed value and then verify the behavior of the APIs `DrawRandomInt`, `DrawRandomDouble`, and the new `DrawRandomBool` that you will work on.

**Comment by nirajvenkat** [comment]
I am interested to contribute to the Q# library and compiler code. Will update with a branch that shows my initial work.
