### ISSUE TITLE
Python API dump_operation does not work if operation has Adj/Ctl specializations

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1178]
**Describe the bug**

Python API `dump_operation()` fails with `Qsc.TypeCk.FunctorMismatch: expected empty set, found Adj + Ctl` error if operation has Adj/Ctl specializations. This doesn't really make sense, since Q# can ignore additional specializations in any other context.

**To Reproduce**

```qsharp
%%qsharp
open Microsoft.Quantum.Arrays;

operation ControlledRxWrapper(
    qs : Qubit[],
    theta : Double
) : Unit is Adj + Ctl {            // Remove "is Adj + Ctl here to make the code work"
    Controlled Rx(Most(qs), (theta, Tail(qs)));
}
```

```python
import qsharp.utils
qsharp.utils.dump_operation("ControlledRxWrapper(_, 1.0)", 2)
```

**Expected behavior**

I expect `dump_operation()` to produce a valid result regardless of specializations the operation has.

**Additional context**

Here is the more detailed error message; looks like the highlighted assignment is too strict in specializations handling.

```QSharpError: Qsc.TypeCk.FunctorMismatch

  × type error
  ╰─▶ expected empty set, found Adj + Ctl
   ╭─[<entry>:1:1]
 1 │ {
 2 │         let op : (Qubit[] => Unit) = ControlledRxWrapper(_, 1.0);
   ·                                      ───────────────────────────
 3 │         use (targets, extra) = (Qubit[2], Qubit[2]);
   ╰────
```

**Comment by swernli** [comment]
This is an oversight on my part regarding the specific type included for the `op` local variable. I think I can take that out and let the type error come from the invocation instead, which should allow for specializations.
