### ISSUE TITLE
Modern QDK doesn't recognize scientific notation with capital E of floating-point numbers

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1179]
**Describe the bug**

I've noticed this for `1E-9`, then I couldn't find a way to write it down using capital E.

**Expected behavior**

I expect scientific notation with capital E to be recognized, same as Classic QDK did. Looking at the `Double.qs` sample, it looks like now only lower-case e is recognized now.

**Comment by idavis** [comment]
@swernli I feel like we discussed this when building the parser, but I can't remember the discussion. We explicitly only check for `e`. We have the same casing limitation with the radix.
```rust
    fn exp(&mut self) -> bool {
        if self.next_if_eq('e') {
            self.chars.next_if(|i| i.1 == '+' || i.1 == '-');
            self.eat_while(|c| c.is_ascii_digit());
            true
        } else {
            false
        }
    }
```
Radix:
```rust
    fn leading_zero(&mut self, c: char) -> Option<Number> {
        if c != '0' {
            return None;
        }

        let radix = if self.next_if_eq('b') {
            Radix::Binary
        } else if self.next_if_eq('o') {
            Radix::Octal
        } else if self.next_if_eq('x') {
            Radix::Hexadecimal
        } else {
            Radix::Decimal
        };
//...
```

**Comment by billti** [comment]
Unless there's a good reason not to, we should support either case.

**Comment by swernli** [comment]
> Unless there's a good reason not to, we should support either case.

Should we fix just `E` or also allow for capital letter radix too? @tcNickolas do you know if the classic QDK accepted both `0x101` and `0X101`?

**Comment by filipw** [comment]
Yes the old QDK accepted capital letters `B`, `O` and `X` for binary, octal and hexadecimal.

**Comment by swernli** [comment]
In that case it's a little more than a one-line change, but it's close, and might make a good first issue. The functions Ian mentioned above would need to be updated to check both characters like so:
```rust
    fn exp(&mut self) -> bool {
        if self.next_if_eq('e') || self.next_if_eq('E') {
            self.chars.next_if(|i| i.1 == '+' || i.1 == '-');
            self.eat_while(|c| c.is_ascii_digit());
            true
        } else {
            false
        }
    }
```
and
```rust
    fn leading_zero(&mut self, c: char) -> Option<Number> {
        if c != '0' {
            return None;
        }

        let radix = if self.next_if_eq('b') || self.next_if_eq('B') {
            Radix::Binary
        } else if self.next_if_eq('o') || self.next_if_eq('O') {
            Radix::Octal
        } else if self.next_if_eq('x') || self.next_if_eq('X') {
            Radix::Hexadecimal
        } else {
            Radix::Decimal
        };
//...
```
And new test cases should be added accordingly.
