### ISSUE TITLE
"entry point not found" IntelliSense error too sensitive for multifile Q# projects

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1180]
**Is your feature request related to a problem? Please describe.**
I'm working with multiple multi-file Q# projects that are covered by Python unit tests (see an example [here](https://github.com/tcNickolas/q-sharp-pocket-guide-samples/tree/qdk1.0/samples/chapter%208/testing)). For such projects, the concept of an entry point does not really make sense, since Python can call any (non-internal?) Q# operation in the code, and different Python tests typically call different Q# operations. The "entry point not found" error is overreacting in this scenario, showing up either in Q# files or in qsharp.json file (the location differs for different projects, I couldn't identify a pattern), and highlighting these files red in VS Code file browser.

**Describe the solution you'd like**
"entry point not found" IntelliSense error not showing up in this scenario. I'm not sure it makes sense as IntelliSense error at all - if the user tries to run Q# code in a way that requires an entry point, this error should show up, but if they don't, they are likely to use it with Python, and this error is just misleading.

**Additional context**
This error also shows up in the katas, where the Q# files are not executed raw but are fed into the backend.

**Comment by swernli** [comment]
I believe this is fixed as of https://github.com/microsoft/qsharp/pull/1737.
