### ISSUE TITLE
Migrate more katas to quantum.microsoft.com

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1185]
There are multiple katas in the Quantum Katas project that cannot be used with the modern QDK, and are straightforward to migrate to the [new katas experience](https://quantum.microsoft.com/en-us/experience/quantum-katas). I don't have detailed notes for each of them, so I think we can track them all in this one issue.

* [x] [BasicGates](https://github.com/microsoft/QuantumKatas/blob/main/BasicGates): makes sense to split it, add tasks 1.1-1.7 to the end of the Single-Qubit Gates kata, 1.8-1.10 - to the end of the Multi-Qubit Systems kata, 2.1-2.6 - to Multi-Qubit Gates kata 
* [x] [Superposition](https://github.com/microsoft/QuantumKatas/blob/main/Superposition): I started migration already, need to finish the rest of the tasks (I've updated the infrastructure to support solutions without adjoint, so we can migrate all content) 
* [x] [Measurements](https://github.com/microsoft/QuantumKatas/blob/main/Measurements) (renamed to Distinguishing Quantum States): add as a standalone kata after Multi-Qubit Measurements, testing infra should be similar to that one
* [x] [DistinguishUnitaries](https://github.com/microsoft/QuantumKatas/blob/main/DistinguishUnitaries): add as a standalone kata after Measurements, needs its own infra but should be similar to existing Measurements 
* [x] [Teleportation](https://github.com/microsoft/QuantumKatas/blob/main/Teleportation): add after DistinguishUnitaries
* [x] [SuperdenseCoding](https://github.com/microsoft/QuantumKatas/blob/main/SuperdenseCoding): add after Teleportation 
* [x] [MarkingOracles](https://github.com/microsoft/QuantumKatas/blob/main/MarkingOracles): add after existing Oracles kata, include tasks 1.5, 1.6, and 1.8 from https://github.com/microsoft/qsharp/issues/1156 (task 1.8 is a building block for majority task from MarkingOracles)

**Comment by jkingdon-ms** [comment]
I will be working on migrating Superposition Kata - Task 1.6 (Bell state)

**Comment by jkingdon-ms** [comment]
I will be working on migrating Superposition Kata - Task 1.7 (All Bell states)

**Comment by jkingdon-ms** [comment]
I will be working on migrating Superposition Kata - Tasks 1.8 & 1.9

**Comment by SakthiVijayS** [comment]
I will be working on migrating Superdense Coding Kata

**Comment by WWhitedogi** [comment]
I will be working on  migrating tasks 1.1-1.7 to Single-Qubit Gates, tasks 1.8-1.10 to Multi-Qubit Systems, tasks 2.1-2.6 to Multi-Qubit Gates.

**Comment by jkingdon-ms** [comment]
I will be working on migrating Superposition Kata - Tasks 1.11, 1.12

**Comment by frtibble** [comment]
I am working on Superposition Task 1.13

**Comment by devikamehra** [comment]
I am working on migration of Teleportation Kata

**Comment by Manvi-Agrawal** [comment]
@tcNickolas, I would like to pick SuperDenseCoding kata

**Comment by jkingdon-ms** [comment]
I will be working on migrating Superposition Kata - Tasks 2.2, 2.3

**Comment by tcNickolas** [comment]
For everyone who will work on a task that relies on the previous tasks' solutions (and we're getting there with teleport and superdense coding protocols): with the current infrastructure, each task of a kata is independent and has no access to the code cells for other tasks.

As a workaround, we can copy-paste the solutions for the tasks on which the current task depends in the placeholder, so that the learner can access them without doing the copy-paste themselves. For example, in the QEC kata I'm working on, encoding task for Shor code uses encoding task for bit flip code, and the placeholder looks like this:

```qsharp
namespace Kata {
    operation ShorEncode (qs : Qubit[]) : Unit is Adj + Ctl {
        // Implement your solution here...
        
    }

    // You might find this helper operation from an earlier task useful.
    operation BitflipEncode (qs : Qubit[]) : Unit is Adj + Ctl {
        CNOT(qs[0], qs[1]);
        CNOT(qs[0], qs[2]);
    }
}
```

**Comment by frtibble** [comment]
I'll work on Superposition Task 2.4 next

**Comment by JPark1023** [comment]
I will start migrating Measurements tasks 2.1-2.3

**Comment by frtibble** [comment]
I will work on Superposition task 1.14

**Comment by moumita-halder** [comment]
I am working on migrating task 1.3 from Workbook_Measurements to Distinguishing States Kata.

**Comment by jkingdon-ms** [comment]
I will be working on migrating Distinguish Unitaries Kata - Tasks 1.2, 1.3, 1.4

**Comment by jkingdon-ms** [comment]
I will be working on migrating Distinguish Unitaries Kata - Tasks 1.5, 1.6, 1.7

**Comment by jkingdon-ms** [comment]
I will be working on the remainder of MarkingOracles.

**Comment by moumita-halder** [comment]
I am migrating tasks 1.4, 1.5 & 1.6 from the Measurements workbook to Distinguishing States Kata.

**Comment by moumita-halder** [comment]
I am migrating tasks 1.10-1.15 from Measurements to Distinguishing States kata.

**Comment by moumita-halder** [comment]
I am migrating tasks 1.07-1.09 from Measurements to Distinguishing States kata.

**Comment by tcNickolas** [comment]
And with the PR #1638 merged last night I declare this issue completed! 

Thank you again to everybody who worked on this!!!
