### ISSUE TITLE
Move MResetZ to Intrinsic namespace?

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1193]
Now that Q# requires resetting qubits to |0> before releasing them, not just measuring them, I find myself using `MResetZ` a lot more often than with the classic QDK, and every time I need to open `Microsoft.Quantum.Measurement` namespace. (There's also no Quick Fix to automate this.)
Moving it to Intrinsic seems logical, since it's so frequently used in the code.

**Comment by tcNickolas** [comment]
I'm not sure moving callables to a namespace that is already in Prelude is a breaking change, since everything from those namespaces is already open by default. (Also, I didn't realize Canon was in the prelude too... Need to go back and update some code :-) )

This approach sounds fine to me. Though now I'm wondering why we have multiple separate namespaces to store callables that are available without opening a namespace...

**Comment by swernli** [comment]
> I'm not sure moving callables to a namespace that is already in Prelude is a breaking change, since everything from those namespaces is already open by default. (Also, I didn't realize Canon was in the prelude too... Need to go back and update some code :-) )

It's a narrow corner case, but if anyone was using the fully qualified name, `Microsoft.Quantum.Measurement.MResetZ` for example, then it would break their code. This is not very likely/common, but the one place where it does come up is when differentiating between two APIs with the same name that are both in scope.

> This approach sounds fine to me. Though now I'm wondering why we have multiple separate namespaces to store callables that are available without opening a namespace...

This is definitely a good thought for our eventual module-based future (@sezna FYI). What does the prelude become and how do we reason about it when we have modules? Should everything in the prelude be in the same module or should multiple modules be in the prelude? Food for thought...

Sound like the one-line change will work for now thought!
