### ISSUE TITLE
DrawRandomInt raise error 

### ISSUE THREAD

**Issue by elibre82** [microsoft/qsharp#1195]
**Describe the bug**

When running the Shor sample algorithm found here : https://github.com/microsoft/qsharp/blob/main/samples/algorithms/Shor.qs
it raise the following problem :

> Qsc.Resolve.NotFound
> 
>   × name error
>   ╰─▶ `DrawRandomInt` not found
>     ╭─[PATH_TO_FILE/shor.qs:53:1]
>  53 │             // integer in the interval [1, number-1]
>  54 │             let generator = DrawRandomInt(1, number - 1);
>     ·                             ─────────────
>  55 │ 
>     ╰────
>   help: found a matching item `Microsoft.Quantum.Random.DrawRandomInt` that
>         is not available for the current compilation configuration

**To Reproduce**

1. In VSCode, create a new text file
2. Save the file as shor.qs
3. in the file, type "sample"
4. Choose "Shor sample" from the list
5. In "Run"  menu, launch "Run without debugging"

I also tried to send a job to azure workspace (Rigetti.sim.qvm), but got the following message:

> The current program contains errors that must be fixed before submitting to Azure

**Expected behavior**

Algorithm that run without a bug

**Screenshots**

**System information**

- VSCode 1.86.2 with "Azure Quantum Development Kit" extension: quantum.qsharp-lang-vscodequantum.qsharp-lang-vscode
- Ubuntu 22.04

**Comment by billti** [comment]
Sounds like you set the profile to 'base profile', which is designed for programs to be submitted to run on hardware. DrawRandomInt is not available in that profile, and you should set to 'unrestricted'. See https://github.com/microsoft/qsharp/wiki/QIR

**Comment by xTye** [comment]
@billti How do we run this on actual hardware though?
