### ISSUE TITLE
Update repo to use Rust 1.76 and fix 1.76 clippy lints

### ISSUE THREAD

**Issue by ozfollowoz** [microsoft/qsharp#1209]
The compiler throws an error when the cont_tup and cont_arr functions in compiler\qsc_eval\src\lib.rs are called with &Vec<ExprId> arguments. The error suggests replacing these with &[ExprId].

**To Reproduce**

Compile the qsc_eval library using cargo clippy --all-targets --all-features -- -D warnings.
Expected behavior

The compilation should succeed without any errors.

**Screenshots**

Not applicable for this bug report.

**System information**

Package/Extension: QSC Eval (qsc_eval)
Operating System: [Please specify your operating system]
IDE (if applicable): [Please specify your IDE, if applicable]
Additional context

The error message suggests using slices (&[_]) instead of vectors (&Vec) as arguments for the cont_tup and cont_arr functions. This is likely because using slices can be more efficient in this case.

**Additional Notes:**

The provided traceback seems unrelated to the specific bug and can be omitted from the report unless relevant for deeper troubleshooting.
You can modify the report title to be more specific, such as "QSC Eval: Error with &Vec in cont_tup and cont_arr functions".

**Version Information**
Detected cargo fmt version: rustfmt 1.7.0-stable (07dca489 2024-02-04)

Detected cargo clippy version: clippy 0.1.76 (07dca489 2024-02-04)

Detected node.js version v20.9.0

Detected wasm-pack version wasm-pack 0.12.1

**Comment by swernli** [comment]
This appears to be a newer lint as of clippy 1.76
