### ISSUE TITLE
Resource Estimator - T states per rotation formula

### ISSUE THREAD

**Issue by bdg221** [microsoft/qsharp#1218]
**Describe the bug**

The formula used by the Resource Estimator for number of T states to implement an arbitrary rotation does not match the cited paper. 

The formula used by the Resource Estimator is:
T ( \epsilon ) = 0.53 log2 ( 1 / \epsilon ) + 5.3

In practice, the number of T states per rotation is:
```
                (NUM_TS_PER_ROTATION_A_COEFFICIENT
                    * ((self.rotation_count as f64) / eps_synthesis).log2()
                    + NUM_TS_PER_ROTATION_B_COEFFICIENT)
                    .ceil() as _,
``` 
[(see logical_counts.rs)](https://github.com/microsoft/qsharp/blob/main/resource_estimator/src/system/data/logical_counts.rs)
where:
```
/// A coefficient in Ts per rotation
pub const NUM_TS_PER_ROTATION_A_COEFFICIENT: f64 = 0.53;

/// A coefficient in Ts per rotation
pub const NUM_TS_PER_ROTATION_B_COEFFICIENT: f64 = 5.3;
```
[(see constants.rs)](https://github.com/microsoft/qsharp/blob/main/resource_estimator/src/system/constants.rs)

This information is seen by the user in the "Resource estimates breakdown" section of the estimate report. For example, the double-factorized chemistry sample shows:

The number of T states to implement a rotation with an arbitrary angle is ⌈0.53log2(11,988,044/0.0033333333333333335)+5.3⌉ [arXiv:2203.10064]. For simplicity, we use this formula for all single-qubit arbitrary angle rotations, and do not distinguish between best, worst, and average cases.

However, the linked paper [arXiv:2203.10064](https://arxiv.org/abs/2203.10064) does not include this formula. 

The table on page 8 of the paper lists a "Mixed fallback" approximation protocol for Clifford+T (T-count) as `0.53 log2 (1/ \epsilon ) + 4.86`  and the "Mix fallback" approximation protocol for Clifford+sqrt(T) (T count) as `0.56 log2 (1 /\epsilon) + 5.30`. 

![image](https://github.com/microsoft/qsharp/assets/62308289/931dab14-23b8-4e13-99c6-570d7f908df2)

**To Reproduce**
N/A

**Expected behavior**

Either the formula should match the paper or an explanation of the formula should be provided.

**Screenshots**

![image](https://github.com/microsoft/qsharp/assets/62308289/1ec9b0b0-888a-4729-941f-52308b78e791)

**System information**
N/A

**Additional context**
N/A

**Comment by msoeken** [comment]
Thanks for catching this @bdg221. We will change 5.3 to 4.86 to match the mixed fallback mean formula for the Clifford+T gate set.
