### ISSUE TITLE
Badge View 

### ISSUE THREAD

**Issue by NATIVE-EARTHLING** [microsoft/qsharp#1248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by billti** [comment]
Can you provide more details? The title alone isn't that helpful. Thanks.

**Comment by ScottCarda-MS** [comment]
Closing this issue out as it isn't clear what the ask is on this issue. If there is a need here, a new issue with more detail can be opened and triaged.
