### ISSUE TITLE
Completions Rework after Hierarchical Namespaces

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#1252]
As they're currently implemented, completions make a lot of assumptions. They only check the global scope for whether or not they need to add an `open` statement, and they take some short cuts with respect to re-triggering completion. Additionally, they don't actually query the resolver for what is in scope at a given point. 

Completions will have to be generally re-worked after hierarchical namespaces go in. We will prefer `import` to `open`, and completions will have to understand that, e.g., `Diagnostics` is a sub-namespace of `Quantum`, which is a sub-namespace of `Microsoft`.

related: #493

**Comment by minestarks** [comment]
Fixed in #1756 , #1947  and other related PRs
