### ISSUE TITLE
SVG images embedded into Katas can be corrupted when creating the npm package

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#1274]
**Describe the bug**

When embedding SVGs into Katas using the `@svg` macro, depending on the image that is embedded, the browser might not display the image in the playground. In these cases, the browser will display some of the code that conforms the image in the place where the image should be.

![image](https://github.com/microsoft/qsharp/assets/6840909/d39567e9-1fac-46fc-b322-1f0fe0b72ca0)

**Comment by cesarzc** [comment]
This issue happens because we embed the SVG into the markdown before transforming it to HTML (using `marked`) to include it into the npm package. The transformation process causes the SVG code to be corrupted so the resulting rendered HTML is not what we expect.

The fix to this issue is to embed the SVG until after markdown has been transformed to HTML.

**Comment by billti** [comment]
SVG is valid HTML, which should be valid markdown and not corrupted. Do you know what specifically is causing this? (e.g. specific SVG constructs or a marked bug?)

**Comment by billti** [comment]
This was actually a corrupt SVG causing the issue - it had `"-nan"` for some numeric values. I fixed it as part of #1438 with this commit <https://github.com/microsoft/qsharp/commit/6725ad5248d145c762d6743f966ea36527c721d5#diff-e517e54b6129a0cd828bffe1f4e2951e434d240536f3411f3084bee292b3d399L21>

CC @tcNickolas as I know this was an outstanding issue for some other work.

**Comment by tcNickolas** [comment]
That issue happened with the files for Deutsch algorithm that never made it to main. You can find them in https://github.com/microsoft/qsharp/compare/mariia/deutsch-img?expand=1. I've just checked that building this branch in the playground (with the latest main) still has this issue.

**Comment by billti** [comment]
Those SVGs aren't valid inline HTML in markdown. They include numerous blank lines between the CSS rules. After Markdown sees an opening tag, it starts treating the following line as inline HTML __until__ it sees a blank line, at which point it goes back to parsing as markdown. (See the `End condition` sections in rules 6. and 7. at <https://spec.commonmark.org/0.31.2/#html-blocks> .

There's a bunch of surprisingly subtle behaviors with HTML embedded in Markdown. For example, notice the difference between content in [spans and divs in this link](https://spec.commonmark.org/dingus/?text=%23%23%20Differences%0A%0A%3Cdiv%3EUnderscores%20are%20_are%20not_%20processed%20as%20emphasis%3C%2Fdiv%3E%0A%0A%3Cspan%3EUnderscores%20_are%20markdown_%20for%20emphasis%3C%2Fspan%3E). I went over it in the last team meeting, but happy to give you an overview. I can add some notes to the markdown and latex guidance too.
