### ISSUE TITLE
Connection string enhancements

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#1283]
It would be nice to:

- Be able to right-click on a workspace and copy the connection string to the clipboard (use the connecting string already used to connect, or fetch it from Azure via AzureAD auth).
- Have the sample Jupyter Notebooks indicate how to use a connection string (e.g. guide users on using the above feature, then setting the `AZURE_QUANTUM_CONNECTION_STRING` environment variable do it).
- Enable the user to right-click on a workspace and update just the API key used to connect. (Currently they have to remove and readd the workspace with the new connection string).

Only minor complication is for first bullet above is it needs to handle if connection strings/API keys are disabled for the workspace.

**Comment by sezna** [comment]
As we have not received any user feedback around this enhancement, this work is not planned.
