### ISSUE TITLE
Controlled rotation gates don't check that target and controls are distinct qubits

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1339]
**Describe the bug**

It is possible to apply Controlled Ry and Rz gates with 2 controls and target that is the same as one of the controls, and have no exception happen.

**To Reproduce**

The smallest repro I could find was:

```qsharp
operation BugDemo() : Unit {
    use qs = Qubit[2];
    ApplyToEach(H, qs);
    Controlled Ry(qs, (0.5, qs[1]));
    ResetAll(qs);
}

BugDemo()
```

Using only one control doesn't trigger the bug (the exception is thrown correctly), and using X instead of Ry also doesn't trigger it.

**Expected behavior**

Controlled gates are not defined for targets that are the same as controls, so I expect an exception for any combination of gates and control/targets that have overlapping controls and targets. (This was the case in Classic QDK too.)

**System information**

- qsharp 1.3.1

**Comment by saram-aman** [comment]
@tcNickolas can you please assign the task to me?

**Comment by swernli** [comment]
@saram-aman This one has some subtlety related to the way that decompositions use qubits that makes it far from easy to resolve. We might need to do some refactoring to actually accomplish this, if it's possible at all.
