### ISSUE TITLE
Review algorithm samples and see if anything suspicious with global phase shows up.

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#1388]
See #1317 for more context.

Some of our samples might use patterns that interact poorly with global phase in a way that can confuse readers of the state dumps. We should review the samples and see if any changes like the qubit scoping for #1370 can mitigate that confusion. In general, samples should avoid nuanced global phase if possible.

This review may result in sub-issues for relevant sample updates or just be closed once samples have been sufficiently reviewed.

**Comment by tcNickolas** [comment]
I skimmed through our algorithms samples, the next most confusing one is Teleportation: it says teleporting one-qubit state but DumpMachine has two qubits. We should be able to use DumpRegister instead to have one-qubit states.

**Comment by swernli** [comment]
Given we have not observed any new phase issues with samples, I'm going to close this issue. We can either reopen or file fresh if a new phase related issue is seen.
