### ISSUE TITLE
Truncate floating-point numbers in alternative state visualization

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1396]
**Is your feature request related to a problem? Please describe.**
DumpMachine prints floating-point numbers in amplitudes with 4 digits of precision, but the same numbers show up with a lot more precision in the alternative state visualization. This looks odd, and I don't think we need that kind of precision.

![image](https://github.com/microsoft/qsharp/assets/10113024/2464eb17-49a9-47c2-bfff-4b715f062f24)

**Describe the solution you'd like**
It probably makes sense to truncate/round floating-point numbers to the same precision as we do in DumpMachine, to make the display consistent.

**Comment by DmitryVasilevsky** [comment]
One can change the line
https://github.com/microsoft/qsharp/blob/2963b42634ca29d8d5dcee58a4f23a95fb5c5a87/compiler/qsc_eval/src/state.rs#L486

**Comment by Manvi-Agrawal** [comment]
@DmitryVasilevsky @tcNickolas I would like to work on this issue.

**Comment by Manvi-Agrawal** [comment]
@tcNickolas , how do I see the lengthy floating point numbers in alternate state visualisation? So far I have tried running below 2 cells in jupyter notebook.

```python
%%qsharp

open Microsoft.Quantum.Diagnostics;

operation BellState() : Unit {
    use q = Qubit[2];
    H(q[0]);
    CNOT(q[0], q[1]);
    DumpMachine();
    ResetAll(q)
}

BellState()
```

![image](https://github.com/microsoft/qsharp/assets/40084144/3d20a551-72c7-4e34-8072-7140454bd5ad)

```python
qsharp.eval("BellState()")
```
Output
```text
STATE:
|00⟩: 0.7071+0.0000𝑖
|11⟩: 0.7071+0.0000𝑖
````

> PS: Running Operation BellState in a .qs file using `@Entrypoint` gives the same output as `qsharp.eval("BellState()")`

**Comment by tcNickolas** [comment]
I saw it in the playground, for example, if you add DumpMachine to Superposition sample (and change H to Ry). 

![image](https://github.com/microsoft/qsharp/assets/10113024/179a4cee-5cea-4a3e-b6ab-d08316026dac)

**Comment by Manvi-Agrawal** [comment]
@tcNickolas, @DmitryVasilevsky  I could get this working now. Thanks for the help.

![image](https://github.com/microsoft/qsharp/assets/40084144/be204da2-5dfd-45e6-9b61-026c382207b0)

I have a question about the intended behavior for decimal values with less than 4 decimal places. Do we need the new behavior to be with padding or without padding?
 
 > PS: I just created a superposition of 2 qubits using H gate on both qubits; dump machine says `0.5000` and not `0.5`, so i think we should be good with padding. Thoughts? 
  ![image](https://github.com/microsoft/qsharp/assets/40084144/c2a12eab-d253-4ec5-945b-e616b90f67a2)

**Comment by tcNickolas** [comment]
Either way can work, I think. The goal of the alternative state visualization is to offer formulas that are easier to read and interpret than just floating-point numbers, so from this point of view 0.5 is better than 0.5000. But we can also aim for consistency with DumpMachine output.

Does this scenario actually occur? The visualization should recognize the value and print it as 1/2 rather than a floating-point number (and the same for a lot of other fractions).

**Comment by Manvi-Agrawal** [comment]
> Does this scenario actually occur? The visualization should recognize the value and print it as 1/2 rather than a floating-point number (and the same for a lot of other fractions).  

Nope, it doesn't. We print fractions in this case. Actually, unit tests caught this case of trailing zeros, so thats why I thought I could ask you. Having 4 digits of precision is short change: `write!(latex, "{:.4}", number.value).expect("Expected to write decimal value."); `, with side effect of trailing zeros. From my brief search it seems, we would either need to use some extension or a different package dependency to remove trailing zeros, or use multiple by 10^4, round the number and then divide by 10^4, which I find a bit ugly.

**Comment by tcNickolas** [comment]
I'm fine with keeping trailing zeros, I don't have strong feelings about one scenario vs the other. Can you clarify what test case has trailing zeros that are not recognized as a fraction? (You can also open a draft PR to run CI build so that everybody can see the failing tests.)
