### ISSUE TITLE
Work in Progress kata list

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/qsharp#1419]
**Is your feature request related to a problem? Please describe.**
 I would appreciate a WIP list(Work in Progress) of katas that get tested in CI and local but not get published. That will give us immunity from accidentally publishing katas to the main website.

**Describe the solution you'd like**
A `work_in_progress.json` file that builds the katas locally in playground and tests it in CI.

**Describe alternatives you've considered**
Adding kata to index.json and removing it before merging PR.

**Additional context**
https://github.com/microsoft/qsharp/pull/1408#discussion_r1575595598

**Comment by Manvi-Agrawal** [comment]
@tcNickolas , created this issue to track my suggestion as discussed.

**Comment by cesarzc** [comment]
@Manvi-Agrawal thank you for creating this issue and providing some options.

The way I would recommend implementing this by adding an `is_published` property to the `Kata` [type](https://github.com/microsoft/qsharp/blob/243ea46dd01bac3076f09a214ddb53782b09ce11/npm/qsharp/src/katas.ts#L65). Once the `Kata` type has this property, the `getAllKatas` [function](https://github.com/microsoft/qsharp/blob/243ea46dd01bac3076f09a214ddb53782b09ce11/npm/qsharp/src/katas.ts#L71C23-L71C34) can be updated to receive an optional `include_unpublished` argument that defaults to `false` and if set to `true` all published and unplublished katas are returned. This can be invoked with this argument set to `true` in tests and in the playground without affecting the main site.
