### ISSUE TITLE
If @[exercise] macro doesn't have new line after it, parser doesn't recognize it as a macro

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1423]
**Describe the bug**

If @[exercise] macro in `solution.md` file doesn't have new line after it, parser doesn't recognize it as a macro and treats it as text. This leads to katas build failure with an extremely confusing error "Exercise ... does not have solutions". (Took me half an hour to figure out what's going on, when the exercise clearly has solutions.)

**To Reproduce**

See PR https://github.com/microsoft/qsharp/pull/1420 for a repro.

**Expected behavior**

Macro is recognized regardless of a new line after it.

**Comment by billti** [comment]
Fixed in #1426
