### ISSUE TITLE
LaTeX doesn't render on first load for some katas

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#1435]
I spent hours debugging this thinking it was changes I made before realizing this is now broken on the site too :-/ , but if you go to the playground <https://microsoft.github.io/qsharp/> and immediately go to the 'Single-qubit gates' or 'Multi-qubit gates' then you'll see the LaTeX fails to render on first load.

I tracked it down to the use of `\color{red]`, which was introduced extensively today in #1424, and a little further back in #1369, both by @WWhitedogi .

On subsequent renders it loads fine, probably as that is part of an extension that loads on first use (still seems to be a MathJax bug). Easiest fix is just to remove the `\color{red}` usage. Is it required?

CC @tcNickolas

**Comment by billti** [comment]
Additional info at <https://docs.mathjax.org/en/latest/input/tex/extensions/colorv2.html#colorv2>. Looks like the usage introduced is "non-standard" and would need to be explicitly enabled. We could do that, or switch to standard usage, or my preference to not use `\color` if not absolutely necessary.

**Comment by billti** [comment]
I accidentally just push a fix for this directly to main. Ooops. Feel free to go check out https://github.com/microsoft/qsharp/commit/587b8b0b628dc35704106806fa60e8a39117be71 if interested.

I'd still suggest not using `\colors` though. (Or else make sure QCOM also pre-loads the package to avoid issues).

**Comment by billti** [comment]
Note that the PR at https://github.com/microsoft/qsharp/pull/1438 updates some of the files containing this new LaTeX. Might want to review that before any major changes to avoid painful merge conflicts.

**Comment by billti** [comment]
FYI: Started a wiki page at https://github.com/microsoft/qsharp/wiki/Markdown-and-LaTeX-guidelines . With your input @tcNickolas  and @WWhitedogi (and other major content contributors), I'd like to flesh out some guidelines here that we try to adhere to. Sound reasonable?

**Comment by tcNickolas** [comment]
> I accidentally just push a fix for this directly to main. Ooops. 

Should we take a look at the branch protections for our main? I think there is a setting to limit pushes from administrators, something along the lines of "Do not allow bypassing the above settings"

On the topic, I think we can replace \color with \textbf - I need some way to highlight specific parts of the formulas, and colors are the easiest ones, but bold should also work.

**Comment by billti** [comment]
Resolved with the push to main referenced above.
