### ISSUE TITLE
Playground Tutorial and Documentation links don't work when combined with "Get link" button.

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#1558]
**Describe the bug**

By using the "Get a link to this code" button and the browser refresh button, you can get the playground in a state where the Tutorial and Documentation links don't work as expected.

**To Reproduce**

1. Open clean playground state.
2. Make some noticeable change to the default code.
3. Click the "Get a link to this code" button. (notice the URL changes)
4. Refresh the page using the browser refresh button.
5. Click on one of the Tutorial links. (notice how the URL resets.)

At this point the erroneous behavior is encountered:
- The page does not display the selected Tutorial.
- Navigating to a different code sample will change the code to the selected sample, but clicking on one of the Tutorials or Documentation links changes it back to the manually altered code, despite the URL never taking on the "link" info again.

**Additional Information**

This was encountered on the Chrome browser.

**Comment by sezna** [comment]
We just reproduced this, so it is still an issue.

**Comment by ggridin** [comment]
I think I have the fix - testing now
