### ISSUE TITLE
Phantom "entry point not found" error in the Playground

### ISSUE THREAD

**Issue by orpuente-MS** [microsoft/qsharp#1577]
**Describe the bug**

I found some bad behavior where the `LanguageService` issues an "entry point not found" error even though the `@EntryPoint` is present.

**To Reproduce**

1. Open the Playground.
2. Click on "Getting Started" (the first tutorial).
3. Click back on "Minimal" (the first sample).
4. You will see the diagnostic in the editor.

**Expected behavior**
After switching back to "Minimal" there shouldn't be any errors.

**Screenshots**

![image](https://github.com/microsoft/qsharp/assets/156957451/6a530dc5-c8b2-4f32-9c33-ae41a7014740)

**System information**

- Version of the package or extension for which the problem occurs: latest main branch
- Your operating system: Windows 11
- For issues with extensions, the version of the IDE for which the problem occurs: Playground

**Additional context**

**Comment by swernli** [comment]
The spot fix that I thought resolved this actually broke other language service features in the playground, so we need to revert it.

**Comment by swernli** [comment]
This is fixed as of recent updates to how we track editor instances with Monaco in the playground.
