### ISSUE TITLE
Bitwise XOR and PowI in new Q#?

### ISSUE THREAD

**Issue by anneriet** [microsoft/qsharp#1595]
I have some old Q# code (v0.something) I am trying to get to work again, and I am running into some issues.

1. I need to do a bitwise XOR between 2 numbers, this used to be the  Xor(int, int) function, but current Xor() function only works for Booleans (was implemented from another issue)

2. I need to raise some numbers to the power of another number. This used to be the PowI(int, int) function. The new Q# has a number of similar functions (like PowC for complex numbers), but none that seem to translate directly to raising an integer to the power of another integer. 

The reason I am grouping this into one feature request is because in different programming languages both of these functions might be done using the symbol "^", but in this context I do not know what is happening if I do "a^b". 

What I would like:

- The new Q# Xor() to function the same way as the old function, to allow bitwise XOR between two integers. 
- To be able to raise an integer to the power of another integer without having to convert them to complex numbers and back.
- To know which of these functions (if any)  happens if I do "a^b"

**Comment by swernli** [comment]
Thanks for the question, @anneriet! In this case, the Q# convention for bitwise operators should clarify things. Q# uses triple symbols for bitwise operations between types that support it (`Int` and `BigInt`) as documented in [Bitwise expressions](https://learn.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/bitwiseexpressions). To summarize here:
 - `&&&` is bitwise AND
 - `|||` is bitwise OR
 - `~~~` is bitwise NOT
 - `^^^` is bitwise XOR

The `^` operator is always exponentiation, and renders the `PowI`, `PowL`, and `PowD` functions obsolete. For the other single symbols, `&` is not used and is a syntax error while `|` is reserved for use in ternary conditional expressions of the form `cond ? true_val | false_val` as seen in [Conditional expressions](https://learn.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/conditionalexpressions).
