### ISSUE TITLE
Use BoolArrayAsKetState to print help messages in CheckOracleImplementsFunction

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1639]
Currently `CheckOracleImplementsFunction` operation used to check that the marking oracle implements the given function prints states on which oracle behaves incorrectly as Boolean arrays. This is fine but a bit lengthy, especially if the inputs have 4 or more (qu)bits.

Migration of Measurements kata brought in a function that can help with that, [BoolArrayAsKetState](https://github.com/microsoft/qsharp/blob/776751989d29e4684dc314811c7ebb7d6511f77b/katas/content/distinguishing_states/Common.qs#L45C14-L45C34). We can move this function to KatasLibrary.qs and use it when [printing "unexpected result" message](https://github.com/microsoft/qsharp/blob/776751989d29e4684dc314811c7ebb7d6511f77b/katas/content/KatasLibrary.qs#L322).

**Comment by ggridin** [comment]
@tcNickolas 
I'd like to work on this issue.

**Comment by tcNickolas** [comment]
Sounds great!

**Comment by ggridin** [comment]
@tcNickolas 
It might make sense to move another helper function IntArrayAsStateName to KatasLibrary.qs
At this case, Common.qs won't have dependency on KatasLibrary
