### ISSUE TITLE
Issue building from source on ARM Mac

### ISSUE THREAD

**Issue by spencerdearman** [microsoft/qsharp#1642]
**Describe the bug**

The primary issue that I am having is that the qsharp package is failing to build on the last step due to a MacOS platform issue.

**To Reproduce**

Run `./build.py` in the root directory as if you were just going to build the package and the error should present itself.

**Expected behavior**

The package should complete building, but instead I receive this error.

`98 files are correctly formatted.
build.py: Finished in 12.408s.
build.py: Building the command line compiler
   Compiling qsharp v0.0.0 (/Users/spencerdearman/qsharp/pip)
error: linking with `cc` failed: exit status: 1
...
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `qsharp` (lib) due to 1 previous error
Traceback (most recent call last):
  File "/Users/spencerdearman/qsharp/./build.py", line 221, in <module>
    subprocess.run(cargo_build_args, check=True, text=True, cwd=root_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--release']' returned non-zero exit status 101.
`

**System information**

Operating System: ARM64 
Chip: M3 Max
MacOS: Sonoma 14.4.1
Python Version: python 3.11.9
Package Version: The default when the repo is downloaded

**Comment by nirajvenkat** [comment]
I was able to make some kludgy fixes to get this working in the short term: 50a20bc38eac7d6dddc182f06dbbff6b6d414fac

**Comment by spencerdearman** [comment]
Thank you Niraj! Unfortunately although it did get further, now I am having this issue:

`error[E0463]: can't find crate for `std`
    |
    = note: the `x86_64-apple-darwin` target may not be installed
    = help: consider downloading the target with `rustup target add x86_64-apple-darwin`

  error[E0463]: can't find crate for `core`
    |
    = note: the `x86_64-apple-darwin` target may not be installed
    = help: consider downloading the target with `rustup target add x86_64-apple-darwin`

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `is_ci` (lib) due to 1 previous error
  warning: build failed, waiting for other jobs to finish...
  error: could not compile `unicode-linebreak` (lib) due to 1 previous error
  error: could not compile `smawk` (lib) due to 1 previous error
  error: could not compile `adler` (lib) due to 1 previous error
  error: could not compile `unicode-width` (lib) due to 1 previous error
  error: could not compile `rustc-demangle` (lib) due to 1 previous error
  error: could not compile `cfg-if` (lib) due to 1 previous error
  error: could not compile `memchr` (lib) due to 1 previous error
  error: could not compile `gimli` (lib) due to 1 previous error
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Failed to build a x86_64 library through cargo
    Caused by: Cargo build finished with "exit status: 101": `CARGO_ENCODED_RUSTFLAGS="-C\u{1f}link-arg=-undefined\u{1f}-C\u{1f}link-arg=dynamic_lookup" MACOSX_DEPLOYMENT_TARGET="10.12" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/spencerdearman/qsharp/qsharp-env/bin/python3" PYTHON_SYS_EXECUTABLE="/Users/spencerdearman/qsharp/qsharp-env/bin/python3" "cargo" "rustc" "--target" "x86_64-apple-darwin" "--message-format" "json-render-diagnostics" "--manifest-path" "/Users/spencerdearman/qsharp/pip/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/qsharp._native.abi3.so"`
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/spencerdearman/qsharp/qsharp-env/bin/python3', '--compatibility', 'off'] returned non-zero exit status 1
  error: subprocess-exited-with-error
  
  × Building wheel for qsharp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/spencerdearman/qsharp/qsharp-env/bin/python3 /Users/spencerdearman/qsharp/qsharp-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /var/folders/zz/1dtb5n794qbf5bn8fxwmn2zw0000gn/T/tmpbghzvou6
  cwd: /Users/spencerdearman/qsharp/pip
  Building wheel for qsharp (pyproject.toml) ... error
  ERROR: Failed building wheel for qsharp
Failed to build qsharp
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/Users/spencerdearman/qsharp/./build.py", line 252, in <module>
    subprocess.run(pip_build_args, check=True, text=True, cwd=pip_src, env=pip_env)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/spencerdearman/qsharp/qsharp-env/bin/python3', '-m', 'pip', 'wheel', '--wheel-dir', '/Users/spencerdearman/qsharp/target/wheels', '-v', '/Users`

This is happening on one of the last steps after it has already run all of the tests.

**Comment by idavis** [comment]
@nirajvenkat Do you have both the aarch64 and x86_64 rust toolchains installed? Can you try running:

```
rustup target add x86_64-apple-darwin
rustup target add aarch64-apple-darwin
```

And then run the build again?

**Comment by spencerdearman** [comment]
I had to run 'rustup target add x86_64-apple-darwin' to get it to work on my device but it was able to build after doing so.

**Comment by billti** [comment]
Interesting that the error was 'ld: symbol(s) not found for architecture arm64' but adding the x64 target fixed it :-/

I'm guessing as we build universal wheels on the mac by default (see https://github.com/microsoft/qsharp/blob/main/build.py#L240), if you build that on Mac (which build.py does by default) then you need both x64 and arm64 targets installed in your Rust toolchain. Maybe our README should include that tidbit.

**Comment by idavis** [comment]
I created #1649 to address this and guide users to a working build.

**Comment by nirajvenkat** [comment]
@idavis Thanks this helps with the full `./build.py`. These changes (https://github.com/microsoft/qsharp/commit/50a20bc38eac7d6dddc182f06dbbff6b6d414) are still required though. My `rustup target list --installed` now shows:
```
aarch64-apple-darwin
wasm32-unknown-unknown
x86_64-apple-darwin
```
Earlier I was only doing `./build.py --wasm --npm --vscode` so the lack of x86_64 toolchain was not affecting me.

**Comment by idavis** [comment]
@nirajvenkat What version of rust are you using? This build works fine for me without any source changes with `1.78`.

**Comment by nirajvenkat** [comment]
@idavis rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by idavis** [comment]
@nirajvenkat #1649 should have fixed your issues. Please reopen if you have any more problems. Thank you!
