### ISSUE TITLE
[Question] Should NeedlessOperation be flagged for something that explicitly returns `Unit`

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/qsharp#1708]
It's worth having something that only returns Unit explicitly as function, or should we support this as a valid operation? In https://github.com/microsoft/qsharp/pull/1687, I coverted `ExplicitReturn` to a function because lint rule was complaining. Prolly we can live with it, but wanted to get other folks opinion on this.

```qsharp
/// # Sample
/// Unit
///
/// # Description
/// The `Unit` type is the singleton type whose only value is ().
/// Functions implicitly return `Unit` if no explicit or implicit
/// return is specified.
namespace MyQuantumApp {

    @EntryPoint()
    function ExplicitReturn() : Unit {
        return ();
    }
    operation NoReturn() : Unit {
        // No return, thus implicitly returning `Unit`.
    }
}
```

**Comment by sezna** [comment]
We think that this is a non-issue, as explicitly returning Unit from an operation is uncommon. We disabled that lint on empty operation bodies primarily for the UX of katas and the samples, as well as when you're in the process of declaring an operation. Once there's a body to the operation, it makes sense for the lint to trigger.
