### ISSUE TITLE
[Question] Samples CI checks and redundancy

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/qsharp#1709]
**Generic questions**
- Edited because of sample validation changes: Samples in `samples.mjs` are checked for lint, hence in #1579 "Getting Started" sample had to be updated for PR to go in. Should we have similar sort of gatekeeping for the **samples not in `samples.mjs`** list? Then we can just rid of duplicate check?

- It might be worth publishing language samples to the same/separate website, if possible, for greater discovery. 

- If option 2 isnt feasible, can we move samples not in samples.mjs list to a new repo? I liked classic QDK samples because they were in a separate repo. @tcNickolas has told me previously that monolith helps to simplify the dependencies. I highly doubt that somebody would likely visit this massive codebase to see these curated samples. Currently, they serve little purpose for both for Q# compiler team and people onboarding to Q#. Maybe add new samples repo as a submodule here if folks think it might be useful, although I know git submodules are a bit annoying.

**Specific questions**
- : Is `QuantumHelloWorld.qs` sample needed when we have Getting started(aka minimal) and superposition sample?
Also, this is **not in `samples.mjs`** list. Interestingly, it does pop up on [samples website](https://quantum.microsoft.com/en-us/experience/quantum-coding) which seems to have been updates a long time back.
![image](https://github.com/microsoft/qsharp/assets/40084144/98b50950-19b5-45c8-8a4c-1271d7ee4b21)

- Is `RandomBit.qs` sample needed when code is very similar to superposition sample? Currently, this is in **samples list** and might be okay to have this duplicate to reiterate that random number can be generated using superposition.

**Comment by sezna** [comment]
This should be resolved when #1797 goes in

**Comment by Manvi-Agrawal** [comment]
Reopening this issue since it has multiple components. #1797 only addressed a part of this issue. Created a separate issue for the follow up of one of the points in #1797 related to the point I raised earlier.

**Comment by Manvi-Agrawal** [comment]
Created separate issues for better triaging since #1797 addresssed a part of this issue and I am unable to reopen this issue
