### ISSUE TITLE
Goto definition on GitHub based dependencies opens the file in single file mode, producing sticky errors

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#1751]
If I go-to-def on something that comes from a dependency, that file that gets loaded into the language server in single file mode and is unaware of the rest of that project, which means any items that come from other files in that project become errors in the problems view:
![image](https://github.com/user-attachments/assets/805e114f-99d0-4da1-a636-38ea8d495f80)
To make matters a little more frustrating, because that is not a real file in the workspace but rather a virtual file downloaded from GitHub, we don't get document close events on it, so the errors never get cleared from the problems view. I can only make them go away by reloading the VS Code window, and they'll come back the next time I trigger go-to-def.

**Comment by sezna** [comment]
Tracked via #1781
