### ISSUE TITLE
Katas preview images can use the wrong theme

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#1763]
The svg images in the katas use colors based on the OS theme preference. However, the playground and kata preview page always use a white background. These means if your OS theme is set to dark, those preview pages have hard to read images.

Either the katas preview pages should use the OS theme (and thus support light and dark mode rendering), or the images should be forced to light mode colors on the preview pages. (Probably should do the former, so that we can preview in both modes for correctness).

**Comment by sezna** [comment]
This has been fixed.
