### ISSUE TITLE
Auto-Imports will Trigger when Unnecessary

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#1775]
**Describe the bug**

When all the items of a namespace are imported with the `*` blob, auto-completes of these items erroneously create unnecessary insert import statements for that specific item. This seems to be the behavior when importing from a remote package.

**To Reproduce**

1. Import a namespace from a remote package using the `*` blob.
2. Begin typing out an item from the namespace.
3. Auto-complete an item from the namespace.

You will see that an auto-import will be inserted into the file for the specific item. This is not necessary as the item is already available via the blob import.

**Edit**

This behavior also seems to repo when importing from the standard library, such as the Math namespace's PI function.

**Comment by tcNickolas** [comment]
I'm getting what looks like the same issue when I have `open Std.Math;` in the file and then type `AbsI` in the code - it will add `import Microsoft.Quantum.Math.AbsI;`
