### ISSUE TITLE
Auto-Imports Cause Duplicate Import Statements

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#1777]
**Describe the bug**

When an item is imported from a namespace, two copies of the item will appear in the completions list. If the user completes with the second option, a duplicate import statement will be automatically inserted. This seems to be the behavior when importing from a remote package.

**To Reproduce**

1. Import an item from a namespace from a remote package.
2. Begin typing out an item from the namespace.
3. Note that there are two instances of the item in the completion list.
4. Auto-complete the item using the second option in the completion list.

You will see that an additional auto-import will be inserted into the file for the specific item. There should only be one option for this item in the completion list, and auto-imports should not create an erroneous duplicate import.

**Edit**

This behavior also seems to repo when importing from the standard library, such as the Math namespace's PI function.

**Comment by tcNickolas** [comment]
This, or something similar, happens to me with 1.8.0 - if I type `import Microsoft.Quantum.Unstable.StatePreparation.Pre` and autocomplete this, I get a second identical import added to the beginning of the file. @sezna Did this fix not make it to 1.8.0, or is it a different issue altogether?

**Comment by ScottCarda-MS** [comment]
> This, or something similar, happens to me with 1.8.0 - if I type `import Microsoft.Quantum.Unstable.StatePreparation.Pre` and autocomplete this, I get a second identical import added to the beginning of the file. @sezna Did this fix not make it to 1.8.0, or is it a different issue altogether?

There is some special logic for the Unstable namespace. Maybe it is specific to Unstable?

**Comment by tcNickolas** [comment]
I just ran into it for non-Unstable: when completing "import Microsoft.Quantum.Convert.IntAs", I ended up with "import Microsoft.Quantum.Convert.IntAsDouble;" twice. I also completed "import Microsoft.Quantum.Co" to "import Microsoft.Quantum.Microsoft.Quantum.Convert", though that one was a single line, so not sure it's the same issue or a separate one
