### ISSUE TITLE
Functors are not available in autocomplete

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1795]
**Describe the bug**

Controlled and Adjoint functors are not available in autocomplete.

**To Reproduce**

Start typing "Contr" or "Adj" and try autocomplete.

**Expected behavior**

These functors are quite commonly used, so I expect them to be available.

**Screenshots**

![image](https://github.com/user-attachments/assets/0b5a2a58-a808-4ba1-9f8e-408621cf961e)
![image](https://github.com/user-attachments/assets/2f9ed398-0f2a-4602-81bd-09eb99f03f6b)

**System information**

- VS Code 1.91.1
- AQDK 1.7.0

**Comment by ScottCarda-MS** [comment]
This seems to have been fixed with the recent updates to completions. Feel free to reopen if you see the issue persist.
