### ISSUE TITLE
Missing API docs for CheckZero, CheckAllZero, DumpMachine

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1822]
**Describe the bug**

There are no API docs for CheckZero, CheckAllZero, DumpMachine on the website.

**To Reproduce**

* https://learn.microsoft.com/en-us/qsharp/api/qsharp-lang/microsoft.quantum.diagnostics/checkzero
* https://learn.microsoft.com/en-us/qsharp/api/qsharp-lang/microsoft.quantum.diagnostics/checkallzero
* https://learn.microsoft.com/en-us/qsharp/api/qsharp-lang/microsoft.quantum.diagnostics/dumpmachine

**Comment by ggridin** [comment]
Also, there is no documentation for DrawRandomBool (that should be in parallel with other random functions)
https://learn.microsoft.com/en-us/qsharp/api/qsharp-lang/microsoft.quantum.random/drawrandomint
