### ISSUE TITLE
Kata playground: Remove profile selection option from tutorial exercises, 

### ISSUE THREAD

**Issue by ggridin** [microsoft/qsharp#1843]
**Is your feature request related to a problem? Please describe.**
Profile selection for Kata tutorials is confusing because Katas only support "unrestricted" profiles.

**Describe the solution you'd like**
Removal of the profile selection option from playground Katas tutorial exercises makes UI cleaner and in line with the production version https://quantum.microsoft.com/en-us/experience/quantum-katas

**Describe alternatives you've considered**
Do not remove profile selection option and keep the UI as is.

![Profile](https://github.com/user-attachments/assets/1e879c97-2bfa-41ce-9d0f-aed59b6ca19b)

**Comment by JPark1023** [comment]
I would like to work on this.
