### ISSUE TITLE
[Question] MathJax previewer for kata

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/qsharp#1879]
For my curiosity :
- Why do we have "Katas MathJax review" at https://microsoft.github.io/qsharp/katas.html?
- How is this different from markdown rendering of katas in playground.

> PS: It might be helpful to mention this tool in katas README, otherwise its difficult for someone to understand the utility of this tool. I got to know how to access this tool from https://github.com/microsoft/qsharp/pull/1798

**Comment by billti** [comment]
You pretty much got it. I'd note both are internal tools for the team to verify before publishing to quantum.microsoft.com, and not intended for general public use, so we don't worry about documenting their reasoning or usage in much detail.
