### ISSUE TITLE
Triage the miette breaking updates

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#1887]
Updating to the latest version of `miette` pulls in a crate, `sys`, which is not available in all of our targets. This issue tracks the work of investigating if we can update without `sys`, and if we want to update to the latest version in general. Deciding we are okay sticking with the current version would be a valid solution to this issue, but we need to do some research to make that decision.

**Comment by billti** [comment]
Looks like https://github.com/zkat/miette/pull/349 should fix this.
