### ISSUE TITLE
RCA panics when comparing arrays

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#1925]
**Describe the bug**

RCA panics when comparing arrays.

```qsharp
operation Main() : Unit {
    use qs = Qubit[2];
    MResetEachZ(qs) == [Zero, Zero];
}
```

**To Reproduce**

[Playground repro](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAEyXMuwrCQBCF4X6f4kAaBXHBUkmnWKWIlybBYpIMyUCym%252ByOWIjvLqvNKT44v7XIcKVpHtlYizOriusRlYJyZ6xNmuHIsQ0yq3iX4DZIhEQQJnEy0Ygywxx8H2iCDqRoyaFhPCN3UP%252Fv4RXkVy8ztL7jrTF%252B5kCpioLErdbY4%252B5E8TYA0htLRI7y2YjWu8fhx8WFI%252BuJ2qFaLXGNPEddcfAbpH0czMd8ASvFFmzXAAAA&profile=adaptive_ri).

Thanks @swernli for finding the bug and providing a repro.

**Comment by orpuente-MS** [comment]
What is the expected behavior here?
