### ISSUE TITLE
Incorrect type error

### ISSUE THREAD

**Issue by anpaz** [microsoft/qsharp#1926]
**Describe the bug**

The compiler is reporting a type error (expected function, found operator) when invoking an operation that takes another operation and calls it as argument.

**To Reproduce**

This simple program. I can't find anything wrong with it:

```
operation Wrapper(q: Qubit, op: (Qubit -> Unit is Adj + Ctl)) : Unit {
    op(q);
}

operation Main() : Result {
    use qubit = Qubit();
    Wrapper(qubit, H);
    return MResetZ(qubit);
}
```

**Expected behavior**

The program should compile and run.

**System information**

This can be reproduced in Q# playground.

**Comment by billti** [comment]
Replace the `->` with a `=>`. The former means function, the latter operation. (Yes, we've discussed this before. Not very intuitive, sadly)
