### ISSUE TITLE
Update GH action versions

### ISSUE THREAD

**Issue by idavis** [microsoft/qsharp#2010]
GitHub is about to [roll out breaking changes](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/) and a few tasks need to be updated.

fuzz.yml
- update `actions/upload-artifact@v3` to `actions/upload-artifact@v4`

devskim.yml
Aside from that, the codeql action `v2` is deprecated and support will end 4 Dec 2024. Need to migrate to [`v3`](https://github.com/github/codeql-action/blob/main/README.md#supported-versions-of-the-codeql-action).

While updating actions, we should also update:

publish-playground.yml
- update `actions/upload-pages-artifact@v1` to `actions/upload-pages-artifact@v3`

**Comment by PratikFandade** [comment]
Hi @idavis, I worked something similar for my projects. can I work on this?

**Comment by minestarks** [comment]
@PratikFandade please feel free to take a stab at it. Please beware though, I don't think external contributors can run GitHub actions on this without permission from the maintainers, so you may not be able to test your changes without a lot of back and forth... so I'm not sure if this is the most suitable task for an external contributor. But go ahead if you're feeling up for it.

**Comment by PratikFandade** [comment]
@minestarks Thanks for the heads-up! I understand the limitations with GitHub actions for external contributors. I'll give it a shot and reach out if any issues come up. Appreciate the opportunity to contribute!
