### ISSUE TITLE
gh pr checkout 2056

### ISSUE THREAD

**Issue by Xlabjun** [microsoft/qsharp#2057]
To access the notebook, open this file in a browser:
    file:///home/jovyan/.local/share/jupyter/runtime/nbserver-473-open.html
Or copy and paste one of these URLs:
    http://(a53c675705c1 or 127.0.0.1):8888/?token=c6338ab860bb6cdf7f976a4676b6a2a8d2e3dc84107a0abd16:45jovyan@a53c675705c1:/workspaces/Quantum/$ jupyter notebook --ip=0.0.0.0127.0.0.1host.pyjovyan@a53c675705c1:/workspaces/Quantum$ cd Samples/src/Teleportation/

_Originally posted by @Xlabjun in https://github.com/microsoft/qsharp/pull/2056#pullrequestreview-2488454032_

**Comment by swernli** [comment]
See https://github.com/microsoft/qsharp/pull/2056#pullrequestreview-2488857942
