### ISSUE TITLE
Expand support for the `Microsoft.Quantum.Arrays` namespace.

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#315]
```[tasklist]
### Tasks
- [x] Implement functions that do would not benefit from lambdas (#324)
- [x] Implement functions for which lambdas would be useful (#350).
```

**Comment by filipw** [comment]
> The ones that I think we should no longer support are the following:

I think it would much nicer if they were all there, but simply marked with a deprecated attribute (and then can be removed at some point later). There is quite some content out there already and having things compile with the existing QDK and not with the new compiler is not great. Backwards compatibility is important, especially where it's not too problematic (no intrinsic implementations). Alternatively, it would be good to have at least an optional bridge/polyfill package that one can include to restore backwards compatibility. 

Already now having https://quantum.microsoft.com/en-us/experience/quantum-coding some of the code from the QDK not be able to compile existing stuff that worked with QDK is very confusing. And the site could be flagged with a warning that your existing code might not work.
