### ISSUE TITLE
Cannot compile partial application with Unit arguments

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp#458]
**Describe the bug**

Partial application for operation with signature `Unit => T` fails.

**To Reproduce**

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAE32OMQvCMBCF9%2F6KGxOQYldLwYoODgF1FYejRii0dyFNkSD976ZtVHTwTQf38b5H2OrOYKVB%2BWOP5Pq2NAYeCYSw0QSqrix3fHNp%2FKeltei7%2FB9yQrpymycTU5PTlrAZYYuuZoKtxfvMbJgbIWEF4xG9Yz7EnpxYLiCTUBSQTcAwF6935Kw%2FcBAI%2BZoTDQpreveeLz%2FNCsmL7xHBECxCymgYkiebKc5WHAEAAA%3D%3D

**Expected behavior**

Should return an array of 10 random Boolean values.

**Additional context**

When adding some parameter to the operation, it works:

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAE32OsQrCMBCG9z7FjQlIaVdLQUUHh4C6isNRIxTau5CmSJC%2Bu2mbIjp4y3H8H%2F93hK3uDFYalD%2F3SK5vt8bAK4EwbDSBqivLHT9cGvN0ay36rviHXJDu3BbJxNTktCVsRtiiq5lgb%2FE5MzvmRhCs4UhOhjXeUT%2FOBwy5yFaQSyhLyCdgmPs3B3LWnzh4hFy%2BiiKFNYml93r7aVZIXnz%2FEgzBkskoGJI3AEF%2BkSIBAAA%3D

**Comment by swernli** [comment]
@samarsha This is an interesting one. Worth noting, it will work if the Unit value is in a variable:
```qsharp
let x = ();
DrawMany(DrawRandomBool, 10, x)
```
