### ISSUE TITLE
.NET ecosystem

### ISSUE THREAD

**Issue by rstm-sf** [microsoft/qsharp#467]
Hello, q# was previously integrated with the .NET ecosystem. How are things now (or planned)?

**Comment by billti** [comment]
The Q# stack being built in this repo has no .NET integration (or dependencies). We've yet to flesh out how we'll integrate across various language platforms and ecosystems beyond Python, JavaScript, and Rust (e.g. .NET, C/C++, Go, etc.)

The core team has started discussing some of these topics informally, but happy to leave this issue open and tag as a "design needed" issue to flesh it out here.

**Comment by general-rishkin** [comment]
I was wondering if there has been any movement on this as I am particularly interested in hybrid computation using Q# with F#.

Is it possible to call Q# from F#?

**Comment by sezna** [comment]
At this point we have no plans to support .NET as an ecosystem. We are happy to revisit this if we see a lot of demand.

**Comment by Thorium** [comment]
For a project in .NET ecosystem, would you rather recommend using the old https://github.com/microsoft/qsharp and the [Nuget package](https://www.nuget.org/packages/Microsoft.Quantum.Compiler) rather than trying to use this and hack some kind of communication to .NET?

**Comment by billti** [comment]
I wouldn't recommend the old qsharp-compiler and NuGet packages for any usage. They are no longer maintained, and the new implementation has made considerable strides in performance and ease of use.

What is your use-case? What type of interoperability is required with .NET? (i.e. how to you envisage the interaction between components/languages for your scenarios)
