### ISSUE TITLE
Wrong corner case in `Padded`

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp#473]
Padding should be possible if the number of initial elements equals the number of total elements. Then no padding takes place.

https://github.com/microsoft/qsharp/blob/20a2f010c45394ac3c95b6002577fa689ac0378b/library/std/arrays.qs#L900

This is correctly implemented in the QDK Libraries:

https://github.com/microsoft/QuantumLibraries/blob/b711a8cf578930e1d731d0c0ac85e3f51b0dedb9/Standard/src/Arrays/Arrays.qs#L271C23-L271C40

**Comment by swernli** [comment]
Fixed by https://github.com/microsoft/qsharp/pull/501
