### ISSUE TITLE
Return statements in lambdas are checked against the surrounding scope's expected return type

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#510]
**Describe the bug**

Return statements within lambda functions unify with the wrong type.

**To Reproduce**

```qsharp
namespace MyQuantumApp {
    @EntryPoint()
    operation Main() : Unit {
        let foo = () => {
            return 42;
        };
        return ();
    }
}
```

The more information you can provide, the more likely someone will be successful at reproducing the issue and finding a fix.

**Expected behavior**

There should not be an error for the line `return 42;` -- the lambda's return type should be inferred as a fresh type variable.

Note that this can be worked around with implicit returns, so the below works:

```qsharp
namespace MyQuantumApp {
    @EntryPoint()
    operation Main() : Unit {
        let foo = () => {
            42
        };
        return ();
    }
}
```

**Comment by ScottCarda-MS** [comment]
Note: I believe that the current behavior of `return` is to return from the most-enclosing _proper_ callable. In this case, even though the `return` is in the lambda, it will return from `Main` and should therefor have type `Unit`. @samarsha is this the correct behavior for `return`?

**Comment by samarsha** [comment]
The current behavior of `return` is to return from the direct parent callable, in this case the lambda.

**Comment by ScottCarda-MS** [comment]
Oh I see, then there is definitely a bug here, with how the typing system handles lambdas. Interestingly the problem doesn't happen for nested callables. For example, this code behaves as expected:
```qsharp
operation Foo() : Int {
    operation Bar() : Double {
        return 3.2;
    }
    Bar();
    return 0;
}
```
