### ISSUE TITLE
Improve qubit efficiency of the `CheckOperationsEquivalence` in the katas library

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#535]
The `CheckOperationsEquivalence` operations uses 2n qubits to check whether two unitary operations are equivalent where n is the input size.

Investigate whether this can be achieved with a single control qubit rather than n control qubits.

**Note**: we probably need to do the math (literally) to make sure using just 1 control qubit would yield the desired result.

**Comment by swernli** [comment]
@DmitryVasilevsky actually already did the math and corrected my thinking on this one (see https://github.com/microsoft/qsharp/pull/855#discussion_r1393435046). So we do need 2n qubits to fully verify the equivalence here. I think we can close this issue.
