### ISSUE TITLE
`Measure` API Improvement to eliminate runtime error

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#585]
Currently, `Measure` expects two arrays that must be the exact same length, or else there is a runtime failure. The first array is an array of `Pauli` values, and the second is an array of qubits to measure.

If we instead wrote `Measure` to take an array of tuples of type `(Pauli, Qubit)`, we could eliminate the possibility of a runtime failure and provide type safety.

**Comment by DmitryVasilevsky** [comment]
Such a change will require repackaging of existing qubit arrays almost always.
