### ISSUE TITLE
Kata examples should be editable and runanble

### ISSUE THREAD

**Issue by DmitryVasilevsky** [microsoft/qsharp#591]
Currently katas in the playground have no way to edit or run examples (in the main index file or in the answer/solution file).

**To Reproduce**

Open any Kata with example "multi-qubit systems" and scroll to any example (for example, Lesson: Multi-qubit systems in Q#). The code will be shown read-only without any buttons to run.

**Expected behavior**

Kata code examples should be editable and runnable just like the default sample in the playground.

**Comment by sezna** [comment]
@DmitryVasilevsky is this done now? It seems katas are editable now on microsoft.github.io/qsharp
