### ISSUE TITLE
Large numbers aren't treated properly

### ISSUE THREAD

**Issue by DmitryVasilevsky** [microsoft/qsharp#632]
**Describe the bug**

Numbers that exceed 64 bits aren't treated properly. They are accepted without errors even without designation 'L'.

**To Reproduce**

```qsharp
namespace MyQuantumProgram {

    @EntryPoint()
    operation Main(): Unit {
        let a = 1000000000000000000000000000;
        let b = 100000000000000000000000000000000000000;
        Message($"{b/a}");
    }
    
}
```
Happily prints 0.

[Code in playground](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACoWLwQqCQBCG7%2FsUg3bQ09a1CDoknQQjeoDRBllwZ5fd8SDiu6fWJSj6DgPz%2Ff%2BvtYYUbmh9R0rPz4VEDLcQBYPQY3GrT%2BFMsQnGi3GsGC1Fjw1BOVx7ZOltFVwb0MKoFMycCpYwVM6wZPlqnKeAyxpKNJzle7izkbkPbzoSQDjCbvubw0e7%2FtP%2BOiwpRmwp2yRjrXFK8lc0rVdN6gkbyP%2BCEwEAAA%3D%3D)

**Expected behavior**

Either fail compilation or treat as long integer. This cannot possible be 0.

**Comment by swernli** [comment]
This is actually intended behavior, see https://github.com/microsoft/qsharp/pull/38. Now that may still be worth a revisit to figure out if we want to have different behavior for values that trigger wrapping, but given the nuances of parsing and the need to support literals that are the minimum 64-bit signed value we may be stuck with this.

**Comment by DmitryVasilevsky** [comment]
@swernli, whatever the internals, I strongly believe we should not allow Int _literals_ that do not fit into int64. Just imagine someone writing BigInt constant and forgetting to put L in the end.

**Comment by swernli** [comment]
I'll review the parsing again and see what alternatives we can explore. I agree it's an easy trap for users to fall into and can lead to bad experiences and buggy code. The trick will be handling negative literals, since today those get parsed as a positive literal and a negate operation...
