### ISSUE TITLE
Floating doc comment consumes to next semicolon or close-curly token as part of recovery

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#652]
When recovering from failing to parse an item, the parser will consume until it hits EOF or a recovery token, namely semicolon or close-curly-bracket. This can trigger weird looking errors when the doc comment is the only text or last text in the namespace, as it consumes the close-curly for the namespace as if it were the malformed item and then causes namespace parsing to fail at EOF:

<img width="388" alt="image" src="https://github.com/microsoft/qsharp/assets/10567287/a744ff5f-93d4-4ac9-a821-f2b2c13bcc07">

[Playground link](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACi2NwQrCMBBE7%2FmKgd7NTxQ9CRb9gTVd7EI3CckWEfHfTaPDXuaxM%2BO9x4AraV7Z%2BWZObCbxgWpUjOeddT5g5BqKZJMUO7ktUtGOoBJFacU0IJf0KKSwhQyBIu6MrfIMS79KPIv0gfYc0swHF0m5ZgqM82vaKNqml3%2FL26FpHzuuiXpsTKHlVDma%2B3wBLgLdT74AAAA%3D)

Not sure how fixable this is, but it does create some confusion during editing while a doc comment is being written before an item is added below it.

**Comment by eureka-cpu** [comment]
Would it make sense to use the same error as if the namespace was empty?

Leaving it empty or with a regular comments throws this error:
```
main.qs@(1,1): entry point not found
help: a single callable with the `@EntryPoint()` attribute must be present if no entry expression is provided
```

Seems that it would be more useful than the present error message at least.

**Comment by swernli** [comment]
I think the PR in #688 is making great progress toward resolving this. Left some comments there!
