### ISSUE TITLE
Type Checking Fails to Catch Lack of Args For Call Exprssion

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#662]
**Describe the bug**

In cases where the callable is returned from a block expression, the type checker doesn't seem to check for the correct arguments to the callable.

**To Reproduce**

```qsharp
namespace Input {
    @EntryPoint()
    operation Main() : Unit {
        {
            Foo
        }();
    }
    operation Foo(x: Int, y: Double, z: String) : Unit {}
}
```
The above code should fail and tell the user that the arguments to `Foo` are missing, but instead it compiles and runs.

**Additional context**
If you add a `Message("Hello")` to the body of `Foo`, you can see that the operation never gets called. Worse, even if you provide the appropriate arguments to `Foo`, it still never gets called.

**Comment by DmitryVasilevsky** [comment]
It doesn't look like () is interpreted as a call here. The following fragment also compiles.

namespace Input {
    @EntryPoint()
    operation Main() : Unit {
        {
            1
        } ();
    }
}

**Comment by ScottCarda-MS** [comment]
Non-issue: The expression block is just next to a unit literal. It isn't interpreting the two together as a call expression. To make it a call expression you can wrap the two in parentheses like this:
```qsharp
namespace Input {
    @EntryPoint()
    operation Main() : Unit {
        ({
            Foo
        }());
    }
    operation Foo(x: Int, y: Double, z: String) : Unit {}
}
```
When doing this, it correctly type-checks the arguments to `Foo` and fails as expected.
