### ISSUE TITLE
Parameters Should Not Shadow Earlier Parameters in the Same Signature

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#665]
**Describe the bug**

Parameters are allowed to shadow earlier parameters in the same signature. This should be an error in Q#.

**To Reproduce**

```qsharp
operation Foo(x: Int, y: Double, x: Bool) : Unit {}
```
Here `x` is defined twice in the parameter list, causing the first `x: Int` to be unusable in the body of the callable.

**Expected behavior**

A design-time error should raised with the user instructing them they cannot define the same parameter multiple times.

**Comment by ScottCarda-MS** [comment]
An additional case to check against is if the parameter for the control register of `controlled` specialization is a duplicate of a parameter of the rest of the callable's signature.
```qsharp
operation Foo(x: Int, y: Double) : Unit is Ctl {
    body ... {}
    controlled (x, ...) {}
}
```

**Comment by swernli** [comment]
> An additional case to check against is if the parameter for the control register of `controlled` specialization is a duplicate of a parameter of the rest of the callable's signature.
> 
> ```qsharp
> operation Foo(x: Int, y: Double) : Unit is Ctl {
>     body ... {}
>     controlled (x, ...) {}
> }
> ```

Oh, this one is much trickier...
