### ISSUE TITLE
Quantum workspace sign-in doesn't work on Safari for iOS/iPad

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#701]
You get the below prompt, but on clicking 'open' nothing happens. It works in Edge for iOS.

<img width="1022" alt="image" src="https://github.com/microsoft/qsharp/assets/993909/4ea65012-947d-4f5a-9550-3e22e5a56a31">

**Comment by swernli** [comment]
I confirmed this is no longer an issue on the latest version.
