### ISSUE TITLE
Empty `Result[]` array should be rejected by QIR codegen

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#725]
Empty arrays can cause problems in processing for providers and tools. Compilation analysis doesn't always know the size of an array, but QIR codegen can catch this at "runtime" when generating the QIR. We'll need to add a new error case to catch this and fail codegen when it is detected.

**Comment by billti** [comment]
This is valid QIR. If hardware can't support this, it should fail in validation for that specific hardware.
