### ISSUE TITLE
App building and ecosystem

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#73]
How does this fit into broader application development? Are there bindings to other languages and environments? For example, can I build a GUI app and link in the qsharp generated code and a simulator?

With the existing QDK there were samples that took advantage of the .NET ecosystem and bindings to pull in packages and build GUI apps etc. that leveraged the QDK. We should have a plan for what our story is in this regard.

**Comment by sezna** [comment]
We have no plans to support languages other than Python in our ecosystem right now.
