### ISSUE TITLE
Quantum Workspaces sign-in prompt is excessively naggy

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#780]
The sign-in prompt appears constantly as I work on non-Q# related parts of the repo.

**To Reproduce**

Install the VS Code QDK extension.

When prompted to sign in, refuse by clicking "Cancel".

![image](https://github.com/microsoft/qsharp/assets/16928427/1bd89b41-8001-4b25-9788-2a0a137c275e)

**Expected**

I won't be asked again.

**Actual**

The modal sign-in dialog keeps interrupting me as I go about my work. It's unclear what's causing it to reappear, but it happens every time I open a Q# file. It also happens when I'm not working with Q# at all - even if don't touch _anything_ and just stare at VS Code for a while, the sign-in prompt appears eventually.

**Extension version** 

v1.0.14

cc @billti

**Comment by billti** [comment]
Thought I already had an issue for this. This occurs if you added a workspace in a prior session, it tries to reload it when you open VS Code for a new session, and the refresh cycle continues to try to reload it every time. Workaround for now is just to remove the workspace if you don't want to sign-in to load it, but agree it should only ask once (or not at all unless you try to view/expand the workspace in tree view)

**Comment by sezna** [comment]
Will revisit if this is an issue going forward.
