### ISSUE TITLE
UDTs formatted incorrectly in type error message (e.g. "expected UDT<Item 1>")

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#811]
**Describe the bug**

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACi3LMQqDQBBG4X5P8ZextlPS2gmRkAOMMiwL7swyjgQR7x4jvvbjCWVeCk2MfhtWEl%2FzyzQaZewBZ8Jf3wqjU8UTb7cksQ0XaWEjTyroKcmjQoOPJL%2FHfzM7RrLmvuv2kiMc4QdqyW2CeAAAAA%3D%3D

```qsharp
namespace MyQuantumProgram {
    newtype Foo = String;

    operation Main() : Unit {
        let bar: Foo = 3;
    }
}
```

Expected: 

`type error: expected Foo, found Int`

Actual:

`type error: expected UDT<Item 1>, found Int`

Seen in commit 8ef55bca

**Comment by ScottCarda-MS** [comment]
Fixed with #862
