### ISSUE TITLE
`@EntryPoint` completion inserts two `@` characters

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#812]
In the Q# Playground or in VS Code, typing `@` in a namespace correctly brings up the `@EntryPoint()` attribute, but committing the completion results in `@@EntryPoint()`.

The insertion range probably needs to consume the `@` before the cursor, which is something I missed initially.

Seen as of a153981617a6c8a2bb745a8d15176755d399af44

**Comment by DmitryVasilevsky** [comment]
Note that similar problem occurs when you change namespace in the "open" statement.
Type "open Microsoft.Quantum.Math;"
Use backspace to remove Math, dot, and a few characters from the word Quantum leaving "Quan".
Type "tum" and dot again to cause auto completion to show hints.
Pick Math from the list and see "open Microsoft.Microsoft.Quantum.Math" in the code.
