### ISSUE TITLE
Type parameters not supported by language service features

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#822]
Type parameters seem to be ignored (and incorrectly formatted in the case of hover & signature help) in language service features.

See:

[playground link](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACm2PzWqDUBCF93mKs1NBSKE7bUM27S5gwD7ANJnqJXFGrmNEiu%2Feq7HQlp7d%2FH3njFDDXUsnxmE89iTWN4XXylODzw2C9i9ifizUicXJ0tGWPZlTwYGcxAkyvImzdX%2FWq2qc5L%2FKxyTHdotab%2BxTdK4Sst4zar626Godsh%2Fc%2BYAC9uGbvaCmzR%2F7sPYUlbuYMkTlPzGubHifZ3gGLfaVwhRn%2FkjhWcLr6T0RziqRYVB%2FQQBH5Wo4fQFjtPH3HwEAAA%3D%3D)

```qsharp
namespace MyQuantumProgram {
    @EntryPoint()
    operation Main() : Unit {
        Foo(3); // hover, signature help show: operation Foo(a : 0) : Unit
    }

    operation Foo<'T>(a: 'T) : Unit {
        let b: 'T = a; // go to def, rename, hover don't work on 'T
    }
}
```

Seen as of 896b3eeb .

**Comment by ScottCarda-MS** [comment]
Fixed with #862
