### ISSUE TITLE
Namespace listed twice in completion hint

### ISSUE THREAD

**Issue by DmitryVasilevsky** [microsoft/qsharp#856]
**Describe the bug**

With the current playground I see Arithmetic namespace listed twice in completion hint.

**To Reproduce**

Go to Playground.
Start typing "open Microsoft.Quantum."
See Arithmetic namespace listed twice.

**Expected behavior**

Arithmetic namespace listed once.

**System information**

Playground as of 11/15/23

**Comment by ScottCarda-MS** [comment]
Resolved with #998
