### ISSUE TITLE
Cannot use Range field names in UDTs

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp#857]
**Describe the bug**

One cannot use `Start`, `End`, and `Step` as field names in UDTs.

**To Reproduce**

See https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAE12OwQrCMAyG732KMDx0sIt6qwgiKngYTHQPUDSMgUtLlyFj9N1tq%2FPgf0n4yB8%2B0h32Vt8RyvEyaOKhq5xpnO5gEhBC%2BOLRItSHG2xBJhZzMkbBmbj4kb12f%2BTKaBNKJN%2BINHdHYjdWpiWWeSLGotPcGoJStyRzUFBTy1%2BDmCcyDA8OBsFDLgtYFbCeH8aU2Pe6QbnIpnCnVNDz8FmD17xGIZ%2BFXqx44cUb38wDZf8AAAA%3D

**Expected behavior**

I don't understand why these field names should be protected.

**Possibly related**

#310

**Comment by ScottCarda-MS** [comment]
Thanks for finding this! I've merged in a fix to the type-checker to allow for these field names with #1037.
