### ISSUE TITLE
Saved quantum workspaces load intermittently

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/qsharp#859]
**Describe the bug**

I have saved Azure Quantum workspaces in my VS Code Extension.

I've found that on page reload, it is intermittent that it sometimes finds the saved workspaces and sometimes doesn't.

For instance, not loaded:
![image](https://github.com/microsoft/qsharp/assets/20933017/353cfeab-d426-4d1a-a501-a14a947bf713)

Then refreshed few times:
![image](https://github.com/microsoft/qsharp/assets/20933017/12c7b2ae-f5bd-4a47-8795-7c60be13c4b5)

Sometimes, I see a flash of my workspaces being found before it resets to the no workspaces view. Maybe it's a race condition?

**To Reproduce**

1. Use the VS Code Extension
2. Login to Quantum Workspaces
3. Add 1 or 2 saved workspaces
4. Refresh the page several times and observe different behaviors (either previous workspaces will show up or you will see the no workspaces view)

**Expected behavior**

Saved workspaces are consistently found and shown, if user is logged in.

**System information**

- Version of extension: v1.0.22
- Browsing vscode.dev on Chrome 118.0.5993.118

**Comment by billti** [comment]
Do you have an old private build of the extension installed by any chance? I see 'Use connection string' in your screen-shot, but that was a prototype I'm not sure we ever shipped to prod (and if we did has been gone for a while). It should just look like the below initially:

<img width="362" alt="image" src="https://github.com/microsoft/qsharp/assets/993909/4321a37d-4419-49c2-8b2f-7997192806cf">

**Comment by xinyi-joffre** [comment]
The versions are included in issue above:

Version of extension: v1.0.22
Browsing vscode.dev on Chrome 118.0.5993.118

I don't see a way to update the extension, and when I say install other version, it only provides these two options:

![image](https://github.com/microsoft/qsharp/assets/20933017/af92c76f-50cf-4a9a-8183-c56d44c54ca9)

Are you using the [DEV BUILD] version?

**Comment by sezna** [comment]
We haven't seen any other reports of this and haven't been able to repro it. @xinyi-joffre, please feel free to re-open if this happens again.
