### ISSUE TITLE
Behavior of division by 0.0 (for `Double`)

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp#870]
**Describe the bug**

This just describes a non-documented inconsistency with the previous QDK. It seems that division by 0.0 returned `NaN` in the previous QDK (see, e.g., [implementation of `NaN()`](https://github.com/microsoft/qsharp-runtime/blob/3af588c549aa7d3d6d512e00e61ab697597b2fed/src/Simulation/QSharpFoundation/Math/FloatingPoint.qs#L22)). The current implementation results in a simulation error and program interruption.

I suggest to have a discussion on whether to change simulation behavior or adding the change to the [simulation section](https://github.com/microsoft/qsharp/wiki/Differences-from-the-previous-QDK#simulation
) of the wiki.

**To Reproduce**

[Q# playground](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAEz1Oy2rDQAy871cMcQ%2F2JZtzS6GHhp4MCUk%2FQLWFI%2FA%2B2JVTQvC%2Fd%2B2EDkKgmdFI1lpUOJGLIxtbhi9WFT8gKyXlfuFWvsIn5y5JVAl%2BZc4XyShFcOLF0YhjhZjCkMhBL6ToyOOHMWXuoeERid8k64Fi7kLPW%2BPJcY7UMdrbcSKvkzs8U%2B7GoOBj7zXdDkG81s3KhMiJlk%2FQkvi6wSu%2BvWhZwBMjK654x267g13627%2FUcs40cP2yWQz367xpHuJsZvMHsuIAuxEBAAA%3D)

**Expected behavior**

I don't suggest an expected behavior, but note the inconsistency.

**Comment by swernli** [comment]
Interestingly, while the C# standard is to allow for infinite and not-a-number representations when division by floating point zero is triggered (see [Floating Point Arithmetic Overflow](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators#floating-point-arithmetic-overflow)), Python will treat any division by floating point zero as an exception. Meanwhile in Rust, `x / 0.0` is either infinite or NaN, just like in C# ([though not everyone is happy about it](https://internals.rust-lang.org/t/should-x-0-be-an-error/2252)).

I'm torn as to whether we should leave the implementation as-is, which matches more of the Python style, or go back to how it worked before when backed by C# and how Rust works while giving users an easy way to introduce infinity, negative infinity, and NaN values into their code. Of note, if we went that route we'd likely also want to re-introduce the stdlib math functions `NaN`, `IsInfinite`, and `IsFinite` to make these values detectable.

@DmitryVasilevsky care to weigh in? Any preference?

**Comment by swernli** [comment]
The more I think about this, the more I'm in favor of restoring the old behavior. I think we can justifiably skip reintroducing `NaN` in the `Microsoft.Quantum.Math` namespace since it would be trivially reproducible with just `0.0 / 0.0`. But we should bring back `IsInfinite` at least (`IsFinite` can be skipped since that is just `(not IsInfinite(x)) and (not IsNaN(x))`, and we can always circle back and introduce it later if we get sufficient requests). I can put up a PR so we see what the scope of the change would be.
