### ISSUE TITLE
Error from Qubit Released in Non-Zero State Causes Leak

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#923]
**Describe the bug**

When releasing a qubit in a non-zero state, a runtime error is thrown. This error may be causing a memory leak.

**To Reproduce**

Run the following code in the playground with 100 shots specified:
```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        H(q);
    }
}
```
You will see the shots become slower and slower.

**Expected behavior**

Shots should be run very fast.

**Additional context**

Similar code with the same runtime error does not have the perf issue:
```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        X(q);
    }
}
```

```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        H(q);
        M(q);
    }
}
```

**Comment by swernli** [comment]
Double-checked and this same issue is present in the VSCode extension, which can cause the webworker to crash:
![image](https://github.com/microsoft/qsharp/assets/10567287/65ad8726-37fb-4c9c-86df-2203304fd42d)
