### ISSUE TITLE
Playground Type Inference Errors Persist After Fix

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#931]
**Describe the bug**

In the playground, some type inference error caused by lack of type information seem to persist even after resolving the issue using type annotations.

**To Reproduce**

The following code correctly issues an error regarding the unknown type of `temp`:
```qsharp
namespace input {

    @EntryPoint()
    operation Main() : Unit {
        let temp = [];
        for i : Int in temp {
            Message($"{i}");
        }
    }
}
```

However, even after applying a type annotation to `temp`: `let temp : Int[] = [];`, the red-squiggles and error message for the type inference error persists. I can see that the error is actually resolved as I can click the "Run" button and the error go away.

**Expected behavior**

The red-squiggle and error message should go away as soon as I fix the issue by adding the type annotation.

**Comment by swernli** [comment]
I'm unable to repro this today on the playground... perhaps there is something different with latest main? @ScottCarda-MS, can you confirm whether you still see this issue?

**Comment by ScottCarda-MS** [comment]
> I'm unable to repro this today on the playground... perhaps there is something different with latest main? @ScottCarda-MS, can you confirm whether you still see this issue?

No I'm definitely still able to reproduce the issue on latest main. I'm running on Windows OS using the Chrome browser, if that helps.

**Comment by swernli** [comment]
Is this with the published playground or locally compiled? I'm using the published playground, but I haven't tried locally compiled.

**Comment by swernli** [comment]
Also, I wonder if this could be a side effect of other bugs where certain things cause language server crashes. If the language server does not restart then nothing clears or regenerates diagnostics, leaving things in whatever the last state was.

**Comment by ScottCarda-MS** [comment]
This is with the locally compiled playground. I can't get the behavior to reproduce on the published playground. The language server doesn't seem like it is crashed. There are not errors reported in the browser console, and other language server features work find.

**Comment by swernli** [comment]
Hmm... I wonder if that points to a subtle race condition issue. The locally hosted playground might be running with different performance characteristics. For me, even trying the locally hosted playground in a few different browsers I can't get it to repro. But I know Dmitry mentioned seeing something like this too, so whatever it is, it's out there.

**Comment by sezna** [comment]
This is difficult to repro, @ScottCarda-MS and @minestarks seem to be the only ones who can repro it. Closing for now, and we can reopen it if we have a deterministic repro.
