### ISSUE TITLE
Cannot document UDT entries

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp#941]
**Describe the bug**

As of recently, I was able to document UDT entries. This doesn't work anymore in current `main`.

**To Reproduce**

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAE4WQT0vEMBDF7%2FkUD3ppQS3uURE8%2BAcPC7uoH2Bsx25gMwnJlKXIfneTVMSbw1zmN%2FNeHun7Hg1eyYUjmz4Pz6xqZUJSispjYZU3eOA0RBvUeqnk7WATchOcFevoiH2DEP0UyUEPpBhI8MGYE49Qv1riFG19IB8PfuQrI%2BQ4BRoY22U%2Fk%2Bjsdj8uX8Ygl%2FBJl8B48h53aCsrVVKMfrhMGovjp4%2BgOF3%2F7suAG7yIXvyj2fzVbFZNRd3tGuH%2BUTQuO29F264SHzhS%2BQxsyUrbZdG7WM2Zy%2FZszuYbAb3J3VwBAAA%3D

**Expected behavior**

No error.

**Comment by sezna** [comment]
Closing as this was resolved in #982
