### ISSUE TITLE
Crash when passing an invalid target profile to the language service `update_configuration` function

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#954]
If an invalid target profile (e.g. `full`) is passed to the language service `update_configuration` function, it crashes.
![image](https://github.com/microsoft/qsharp/assets/6840909/7100ceb6-2743-4e74-80c9-b056bfb81025)

We should fail gracefully providing a useful error message when an invalid target profile is passed to the `update_configuration` function.

**Comment by sezna** [comment]
I think we can close this issue now. If you turn off all typechecking and forcefully pass in an invalid profile, you get a better error message now (I set the profile to `test`):
<img width="426" alt="image" src="https://github.com/user-attachments/assets/2e03ffa3-b8e7-46c2-a40b-33c93cbd2531">
