### ISSUE TITLE
Need better error placement for return type mismatch in case when actual type is Unit

### ISSUE THREAD

**Issue by DmitryVasilevsky** [microsoft/qsharp#970]
**Describe the bug**

When the declared return type of a function doesn't match the actual type returned, an error message is produced. The error message is bound to the last statement, which doesn't always produce intuitive results. For example, if a function is declared as returning Int, but the return statement is actually missing, the last statement (producing Unit) is underlined. It may be a large statement, which makes it not appealing visually and makes it a bit misleading.

Moreover, when you are just writing code and haven't gotten to the last return statement yet, this error gets in the way and is very annoying. It also masks other errors in the code you are typing.

**To Reproduce**

https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAACnWLywqCQBhG9%2FMUHxKiRKLbQmjTUrC20WKKXxlwZmQuoMi8exgtmqKz%2By5HcUl25A9CM589V87L1ujecImFAcDxpJyZWy2Uy%2FJXo0cy3Amt0HChshx7XMj6wV1vb2el0wYCQqEsiqr8GFakd%2Fw%2BECbUKA%2FRJDoIpGmKCnWNb3HFksOEbY0qNgNosPRX2P0KUWrIWt5TtkmWKSQ5i1%2BBBfYEtHZmjiwBAAA%3D

Also in VS Code:

![image](https://github.com/microsoft/qsharp/assets/60718360/0a4e5a96-9d29-48f7-bb3b-0671bf33f70d)

**Expected behavior**

Maybe we should treat the mismatch case when the actual return type is Unit as a missing return. In this case, it would probably make more sense to bind the error to the return type rather than the last satatement.

**Comment by swernli** [comment]
I like the idea of treating `Unit` as a special case to highlight the error differently. We can then have help text that nudges the user toward understanding that they are missing a return or final expression.

**Comment by swernli** [comment]
@DmitryVasilevsky @sezna What do you think of this change:
![image](https://github.com/microsoft/qsharp/assets/10567287/61585263-910c-4797-9b86-265e3b930539)
With the changes in-progress at the linked commit, the error is swapped such that the constraint acts on the return type instead. It's shorter, and the underline only changes like this if the type of the block is known to be `Unit`.
