### ISSUE TITLE
Conditional compilation for individual capabilities

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#996]
We currently support `@Config(Base)` and `@Config(Full)`. But, eventually, we will want to conditionally compile code for individual capabilities. See #882 for additional context.

This syntax could also be used to opt a Q# project in to new language features, like new UDT syntax. Similar to Rust's `#!` or Haskell's language extensions. See #543 for more context on that.

**Comment by cesarzc** [comment]
@sezna if you start working on this, could we sync to talk through some options to make sure we can use it in the multiple scenarios conditional compilation would be useful?

**Comment by sezna** [comment]
@swernli says we've done this, he will verify.

**Comment by swernli** [comment]
Fixed by https://github.com/microsoft/qsharp/pull/1393
